/-
Copyright (c) 2026 Fabrizio Montesi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabrizio Montesi
-/

module

public import Cslib.Foundations.Data.OmegaSequence.Defs
public import Cslib.Logics.Modal.Unary.Basic

/-! # Linear Temporal Logic

This module presents Linear Temporal Logic (LTL) as an instantiation of the general modal-logic
framework.

An LTL `Model` consists of an `ωSequence State` and a valuation of atoms at states. `Model.toModal`
converts it into a modal model whose worlds are positions in the sequence, together with an
auxiliary anchor used to express intervals. Atomic propositions are interpreted on the actual state
occurring at the current position of the sequence.

The modal signature contains three unary operators:

* `next`, which moves to the immediately following position;
* `seek`, which chooses a position in the future and records the current position as an anchor;
* `between`, which ranges over the positions between the anchor and the current position.

The standard LTL operators are then derived. In particular,

`φ U ψ = d⟨seek⟩(ψ ∧ d[between]φ)`.

Thus, at position `n`, `φ U ψ` holds exactly when there is a `k ≥ n` where `ψ` holds and `φ` holds
at every position `j` with `n ≤ j < k`.

`IsLTL` identifies the standard LTL fragment inside the modal syntax. `Proposition` is the subtype
of modal propositions in this fragment. Its constructors preserve the fragment automatically.
Raw uses of `between` can observe the anchor, whereas LTL propositions cannot
(`Satisfies.anchor_iff`). All satisfaction judgements use the generic modal semantics.

For ordinary use, write `⇓LTL[m,n ⊨ φ]` to evaluate `φ` at position `n`, or `⇓LTL[m ⊨ φ]`
to evaluate it at the start of the sequence. These are abbreviations for modal judgements with
an internal anchor fixed to zero. The `Satisfies.at_*` lemmas expose the usual temporal semantics
using only sequence positions, including Boolean connectives backed by the generic modal lemmas.

## Notation

Open `Cslib.Logic.Modal.LTL` for `X` (next), `F` (eventually), `G` (always), `U` (until),
`R` (release), and the judgements `LTL[m,n ⊨ φ]` and `LTL[m ⊨ φ]`.
The unary operators have precedence 40, as in BTL; `U` and `R` are right-associative with
precedence 35. For example, `G F φ` means `φ.eventually.always`.
-/

@[expose] public section

namespace Cslib.Logic.Modal.LTL

open PFunctor
open scoped Proposition Satisfies InferenceSystem

universe u v

variable {State : Type u} {Atom : Type v}

/-! ## Signature -/

/-- Primitive modal operators used to present LTL. -/
inductive Operator where
  | next
  | seek
  | between

/-- The modal signature used to present LTL. All primitive operators are unary. -/
abbrev τLTL : PFunctor := PFunctor.mkUnary Operator

/-- The underlying modal syntax used to encode LTL. -/
abbrev RawProposition (Atom : Type v) := Modal.Proposition τLTL Atom

/-! ## Temporal operators on modal syntax -/

/-- Next: `φ` holds at the immediately following position. -/
abbrev RawProposition.next (φ : RawProposition Atom) : RawProposition Atom :=
  d⟨Operator.next⟩φ

/-- Until: `ψ` holds at some future position, and `φ` holds at every position before it starting
from the current one. -/
abbrev RawProposition.until (φ ψ : RawProposition Atom) : RawProposition Atom :=
  d⟨Operator.seek⟩(ψ ∧ d[Operator.between]φ)

/-- Eventually: `φ` holds at some position at or after the current one. -/
abbrev RawProposition.eventually (φ : RawProposition Atom) : RawProposition Atom :=
  RawProposition.until ⊤ φ

/-- Always: `φ` holds at every position at or after the current one. -/
abbrev RawProposition.always (φ : RawProposition Atom) : RawProposition Atom :=
  ¬RawProposition.eventually (¬φ)

/-- Release, dual to until. -/
abbrev RawProposition.release (φ ψ : RawProposition Atom) : RawProposition Atom :=
  ¬RawProposition.until (¬φ) (¬ψ)

/-! ## The standard LTL fragment

This predicate restricts the existing modal propositions; it does not introduce another syntax.
Its constructors also provide an induction principle for standard LTL formulas.
-/

/-- The fragment generated by atoms, Boolean connectives, next, and until. -/
inductive IsLTL : RawProposition Atom → Prop where
  /-- An atomic proposition is an LTL formula. -/
  | atom (p : Atom) : IsLTL (.atom p)
  /-- Falsity is an LTL formula. -/
  | false : IsLTL ⊥
  /-- LTL is closed under negation. -/
  | not {φ} : IsLTL φ → IsLTL (¬φ)
  /-- LTL is closed under disjunction. -/
  | or {φ ψ} : IsLTL φ → IsLTL ψ → IsLTL (φ ∨ ψ)
  /-- LTL is closed under next. -/
  | next {φ} : IsLTL φ → IsLTL φ.next
  /-- LTL is closed under until. -/
  | until {φ ψ} : IsLTL φ → IsLTL ψ → IsLTL (φ.until ψ)

namespace IsLTL

/-- Truth belongs to the LTL fragment. -/
theorem true : IsLTL (⊤ : RawProposition Atom) := .not .false

/-- The LTL fragment is closed under conjunction. -/
theorem and {φ ψ : RawProposition Atom} (hφ : IsLTL φ) (hψ : IsLTL ψ) :
    IsLTL (φ ∧ ψ) := .not (.or (.not hφ) (.not hψ))

/-- The LTL fragment is closed under implication. -/
theorem imp {φ ψ : RawProposition Atom} (hφ : IsLTL φ) (hψ : IsLTL ψ) :
    IsLTL (φ → ψ) := .or (.not hφ) hψ

/-- The LTL fragment is closed under bi-implication. -/
theorem iff {φ ψ : RawProposition Atom} (hφ : IsLTL φ) (hψ : IsLTL ψ) :
    IsLTL (φ ↔ ψ) := (hφ.imp hψ).and (hψ.imp hφ)

/-- The LTL fragment is closed under eventually. -/
theorem eventually {φ : RawProposition Atom} (hφ : IsLTL φ) :
    IsLTL φ.eventually := .until .true hφ

/-- The LTL fragment is closed under always. -/
theorem always {φ : RawProposition Atom} (hφ : IsLTL φ) :
    IsLTL φ.always := hφ.not.eventually.not

/-- The LTL fragment is closed under release. -/
theorem release {φ ψ : RawProposition Atom} (hφ : IsLTL φ) (hψ : IsLTL ψ) :
    IsLTL (φ.release ψ) := (hφ.not.until hψ.not).not

end IsLTL

/-! ## LTL propositions -/

/-- An LTL proposition is a modal proposition in the standard LTL fragment. -/
abbrev Proposition (Atom : Type v) := {φ : Modal.Proposition τLTL Atom // IsLTL φ}

/-- An atomic LTL proposition. -/
abbrev Proposition.atom (p : Atom) : Proposition Atom := ⟨.atom p, .atom p⟩

instance : Coe Atom (Proposition Atom) := ⟨Proposition.atom⟩

/-- Falsity. -/
abbrev Proposition.false : Proposition Atom := ⟨⊥, .false⟩

/-- Truth. -/
abbrev Proposition.true : Proposition Atom := ⟨⊤, IsLTL.true⟩

/-- Negation. -/
abbrev Proposition.not (φ : Proposition Atom) : Proposition Atom :=
  ⟨¬φ.val, .not φ.property⟩

/-- Disjunction. -/
abbrev Proposition.or (φ ψ : Proposition Atom) : Proposition Atom :=
  ⟨φ.val ∨ ψ.val, .or φ.property ψ.property⟩

/-- Conjunction. -/
abbrev Proposition.and (φ ψ : Proposition Atom) : Proposition Atom :=
  ⟨φ.val ∧ ψ.val, φ.property.and ψ.property⟩

/-- Implication. -/
abbrev Proposition.imp (φ ψ : Proposition Atom) : Proposition Atom :=
  ⟨φ.val → ψ.val, φ.property.imp ψ.property⟩

/-- Bi-implication. -/
abbrev Proposition.iff (φ ψ : Proposition Atom) : Proposition Atom :=
  ⟨φ.val ↔ ψ.val, φ.property.iff ψ.property⟩

instance : Bot (Proposition Atom) := ⟨Proposition.false⟩
instance : Top (Proposition Atom) := ⟨Proposition.true⟩
instance : HasNot (Proposition Atom) := ⟨Proposition.not⟩
instance : HasOr (Proposition Atom) := ⟨Proposition.or⟩
instance : HasAnd (Proposition Atom) := ⟨Proposition.and⟩
instance : HasImp (Proposition Atom) := ⟨Proposition.imp⟩
instance : HasIff (Proposition Atom) := ⟨Proposition.iff⟩

/-- Next: `φ` holds at the immediately following position. -/
abbrev Proposition.next (φ : Proposition Atom) : Proposition Atom :=
  ⟨RawProposition.next φ.val, .next φ.property⟩

/-- Strong until: `ψ` eventually holds, and `φ` holds at every preceding position. -/
abbrev Proposition.until (φ ψ : Proposition Atom) : Proposition Atom :=
  ⟨RawProposition.until φ.val ψ.val, .until φ.property ψ.property⟩

/-- Eventually: `φ` holds at some position at or after the current one. -/
abbrev Proposition.eventually (φ : Proposition Atom) : Proposition Atom :=
  ⟨RawProposition.eventually φ.val, φ.property.eventually⟩

/-- Always: `φ` holds at every position at or after the current one. -/
abbrev Proposition.always (φ : Proposition Atom) : Proposition Atom :=
  ⟨RawProposition.always φ.val, φ.property.always⟩

/-- Release, dual to until. -/
abbrev Proposition.release (φ ψ : Proposition Atom) : Proposition Atom :=
  ⟨RawProposition.release φ.val ψ.val, φ.property.release ψ.property⟩

/-! Operator notation for LTL. -/

@[inherit_doc Proposition.next] scoped prefix:40 "X" => Proposition.next
@[inherit_doc Proposition.eventually] scoped prefix:40 "F" => Proposition.eventually
@[inherit_doc Proposition.always] scoped prefix:40 "G" => Proposition.always
@[inherit_doc Proposition.until] scoped infixr:35 " U " => Proposition.until
@[inherit_doc Proposition.release] scoped infixr:35 " R " => Proposition.release

@[simp, scoped grind =, modal =]
theorem Proposition.val_atom (p : Atom) :
    (Proposition.atom p).val = Modal.Proposition.atom p := rfl

@[simp, scoped grind =, modal =]
theorem Proposition.val_false :
    (⊥ : Proposition Atom).val = ⊥ := rfl

@[simp, scoped grind =, modal =]
theorem Proposition.val_true :
    (⊤ : Proposition Atom).val = ⊤ := rfl

@[simp, scoped grind =, modal =]
theorem Proposition.val_not (φ : Proposition Atom) :
    (¬φ).val = ¬φ.val := rfl

@[simp, scoped grind =, modal =]
theorem Proposition.val_or (φ ψ : Proposition Atom) :
    (φ ∨ ψ).val = (φ.val ∨ ψ.val) := rfl

@[simp, scoped grind =, modal =]
theorem Proposition.val_and (φ ψ : Proposition Atom) :
    (φ ∧ ψ).val = (φ.val ∧ ψ.val) := rfl

@[simp, scoped grind =, modal =]
theorem Proposition.val_imp (φ ψ : Proposition Atom) :
    (φ → ψ).val = (φ.val → ψ.val) := rfl

@[simp, scoped grind =, modal =]
theorem Proposition.val_iff (φ ψ : Proposition Atom) :
    (φ ↔ ψ).val = (φ.val ↔ ψ.val) := rfl

@[simp, scoped grind =, modal =]
theorem Proposition.val_next (φ : Proposition Atom) :
    φ.next.val = RawProposition.next φ.val := rfl

@[simp, scoped grind =, modal =]
theorem Proposition.val_until (φ ψ : Proposition Atom) :
    (φ.until ψ).val = RawProposition.until φ.val ψ.val := rfl

@[simp, scoped grind =, modal =]
theorem Proposition.val_eventually (φ : Proposition Atom) :
    φ.eventually.val = RawProposition.eventually φ.val := rfl

@[simp, scoped grind =, modal =]
theorem Proposition.val_always (φ : Proposition Atom) :
    φ.always.val = RawProposition.always φ.val := rfl

@[simp, scoped grind =, modal =]
theorem Proposition.val_release (φ ψ : Proposition Atom) :
    (φ.release ψ).val = RawProposition.release φ.val ψ.val := rfl

/-! ## Temporal frame -/

/-- A temporal position with an auxiliary anchor.

`now` is the position at which propositions are evaluated. `anchor` is semantic bookkeeping used by
`until` to remember the beginning of an interval.
-/
structure Point where
  /-- Current position in the sequence. -/
  now : ℕ
  /-- Beginning of the interval selected by `seek`. -/
  anchor : ℕ

/-- The accessibility relation associated with each primitive LTL operator.

At a point `(n, a)`:

* `next` reaches exactly `(n + 1, a)`;
* `seek` reaches any `(k, n)` with `n ≤ k`;
* from `(k, n)`, `between` reaches exactly the points `(j, n)` with `n ≤ j < k`.
-/
def relation : Operator → Point → Point → Prop
  | .next, p, q =>
      q = ⟨p.now + 1, p.anchor⟩
  | .seek, p, q =>
      ∃ k, p.now ≤ k ∧ q = ⟨k, p.now⟩
  | .between, p, q =>
      ∃ j, p.anchor ≤ j ∧ j < p.now ∧ q = ⟨j, p.anchor⟩

/-- The canonical frame for LTL. -/
def Frame.ltl : Frame Point τLTL :=
  Frame.ofRelations relation

@[simp, scoped grind _=_, modal _=_]
theorem Frame.ltl_diagonal_iff (op : Operator) (p q : Point) :
    Frame.ltl.diagonal op p q ↔ relation op p q := by
  rfl

/-! ## Models over traces -/

/-- An LTL model consists of an infinite sequence and a valuation of atoms at its states. -/
structure Model (State : Type u) (Atom : Type v) where
  /-- The infinite sequence of states. -/
  seq : ωSequence State
  /-- Valuation of atoms at states. -/
  v : State → Atom → Prop

/-- Converts an LTL model into a unary modal model.

The auxiliary anchor is invisible to atomic propositions: atoms are evaluated only on the state
`m.seq p.now` occurring at the current position.
-/
def Model.toModal (m : Model State Atom) : Modal.Model Point τLTL Atom where
  toFrame := Frame.ltl
  v p a := m.v (m.seq p.now) a

@[simp, scoped grind =, modal =]
theorem Model.toModal_toFrame (m : Model State Atom) :
    m.toModal.toFrame = Frame.ltl := rfl

@[scoped grind =, modal =]
theorem Model.toModal_diagonal_iff
    (m : Model State Atom)
    (op : Operator) (p q : Point) :
    m.toModal.toFrame.diagonal op p q ↔ relation op p q := by
  rfl

@[scoped grind =, modal =]
theorem Satisfies.toModal_atom_iff
    (m : Model State Atom)
    (n a : ℕ) (p : Atom) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ p] ↔ m.v (m.seq n) p := by
  rfl

/-- Atomic propositions can be taken directly to be predicates on states. -/
abbrev StateAtom (State : Type u) := State → Prop

/-- The canonical LTL model when atoms are predicates on states. -/
def Model.ofTracePredicates (t : ωSequence State) :
    Model State (StateAtom State) :=
  ⟨t, fun s P => P s⟩

@[scoped grind =, modal =]
theorem Satisfies.ofTracePredicates_atom_iff
    (t : ωSequence State) (n a : ℕ) (P : StateAtom State) :
    ⇓Modal[(Model.ofTracePredicates t).toModal,⟨n, a⟩ ⊨ P] ↔ P (t n) := by
  rfl

/-- A modal judgement at a sequence position, with the auxiliary anchor hidden.

For standard LTL formulas the choice of anchor is immaterial (`Satisfies.at_iff`).
-/
abbrev judgementAt (m : Model State Atom) (n : ℕ) (φ : Proposition Atom) :
    Modal.Judgement Point τLTL Atom :=
  Modal.Judgement.mk m.toModal ⟨n, 0⟩ φ.val

/-- Evaluate an LTL formula at a sequence position, using the modal inference system. -/
scoped notation "LTL[" m "," n " ⊨ " φ "]" => judgementAt m n φ

/-- Evaluate an LTL formula at the start of a sequence. -/
scoped notation "LTL[" m " ⊨ " φ "]" => judgementAt m 0 φ

/-! ## Semantics of the primitive temporal modalities -/

@[scoped grind =, modal =]
theorem Satisfies.raw_next_iff
    (m : Model State Atom)
    (n a : ℕ) (φ : RawProposition Atom) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ φ.next] ↔
      ⇓Modal[m.toModal,⟨n + 1, a⟩ ⊨ φ] := by
  change
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ d⟨Operator.next⟩φ] ↔
      ⇓Modal[m.toModal,⟨n + 1, a⟩ ⊨ φ]
  rw [Cslib.Logic.Modal.Satisfies.dynDiamond_iff_exists]
  constructor
  · rintro ⟨q, hr, hφ⟩
    have hq := (Model.toModal_diagonal_iff m .next ⟨n, a⟩ q).mp hr
    change q = ⟨n + 1, a⟩ at hq
    subst q
    exact hφ
  · intro hφ
    refine ⟨⟨n + 1, a⟩, ?_, hφ⟩
    apply (Model.toModal_diagonal_iff m .next ⟨n, a⟩ ⟨n + 1, a⟩).mpr
    rfl

@[scoped grind =, modal =]
theorem Satisfies.seek_iff
    (m : Model State Atom)
    (n a : ℕ) (φ : RawProposition Atom) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ d⟨Operator.seek⟩φ] ↔
      ∃ k, n ≤ k ∧ ⇓Modal[m.toModal,⟨k, n⟩ ⊨ φ] := by
  rw [Cslib.Logic.Modal.Satisfies.dynDiamond_iff_exists]
  constructor
  · rintro ⟨q, hr, hφ⟩
    have hq := (Model.toModal_diagonal_iff m .seek ⟨n, a⟩ q).mp hr
    change ∃ k, n ≤ k ∧ q = ⟨k, n⟩ at hq
    rcases hq with ⟨k, hnk, rfl⟩
    exact ⟨k, hnk, hφ⟩
  · rintro ⟨k, hnk, hφ⟩
    refine ⟨⟨k, n⟩, ?_, hφ⟩
    apply (Model.toModal_diagonal_iff m .seek ⟨n, a⟩ ⟨k, n⟩).mpr
    exact ⟨k, hnk, rfl⟩

@[scoped grind =, modal =]
theorem Satisfies.between_iff
    (m : Model State Atom)
    (k n : ℕ) (φ : RawProposition Atom) :
    ⇓Modal[m.toModal,⟨k, n⟩ ⊨ d[Operator.between]φ] ↔
      ∀ j, n ≤ j → j < k → ⇓Modal[m.toModal,⟨j, n⟩ ⊨ φ] := by
  rw [Cslib.Logic.Modal.Satisfies.dynBox_iff_forall]
  constructor
  · intro h j hnj hjk
    apply h ⟨j, n⟩
    apply (Model.toModal_diagonal_iff m .between ⟨k, n⟩ ⟨j, n⟩).mpr
    exact ⟨j, hnj, hjk, rfl⟩
  · intro h q hr
    have hq := (Model.toModal_diagonal_iff m .between ⟨k, n⟩ q).mp hr
    change ∃ j, n ≤ j ∧ j < k ∧ q = ⟨j, n⟩ at hq
    rcases hq with ⟨j, hnj, hjk, rfl⟩
    exact h j hnj hjk

/-! ## Semantics of temporal operators on modal syntax -/

@[scoped grind =, modal =]
theorem Satisfies.raw_until_iff
    (m : Model State Atom)
    (n a : ℕ) (φ ψ : RawProposition Atom) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ φ.until ψ] ↔
      ∃ k, n ≤ k ∧
        ⇓Modal[m.toModal,⟨k, n⟩ ⊨ ψ] ∧
        ∀ j, n ≤ j → j < k → ⇓Modal[m.toModal,⟨j, n⟩ ⊨ φ] := by
  change
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨
      d⟨Operator.seek⟩(ψ ∧ d[Operator.between]φ)] ↔ _
  rw [Satisfies.seek_iff]
  constructor
  · rintro ⟨k, hnk, hk⟩
    rw [Cslib.Logic.Modal.Satisfies.and_iff_and] at hk
    rcases hk with ⟨hψ, hbetween⟩
    rw [Satisfies.between_iff] at hbetween
    exact ⟨k, hnk, hψ, hbetween⟩
  · rintro ⟨k, hnk, hψ, hφ⟩
    refine ⟨k, hnk, ?_⟩
    rw [Cslib.Logic.Modal.Satisfies.and_iff_and, Satisfies.between_iff]
    exact ⟨hψ, hφ⟩

@[scoped grind =, modal =]
theorem Satisfies.raw_eventually_iff
    (m : Model State Atom)
    (n a : ℕ) (φ : RawProposition Atom) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ φ.eventually] ↔
      ∃ k, n ≤ k ∧ ⇓Modal[m.toModal,⟨k, n⟩ ⊨ φ] := by
  change ⇓Modal[m.toModal,⟨n, a⟩ ⊨ (⊤ : RawProposition Atom).until φ] ↔ _
  rw [Satisfies.raw_until_iff]
  constructor
  · rintro ⟨k, hnk, hφ, _⟩
    exact ⟨k, hnk, hφ⟩
  · rintro ⟨k, hnk, hφ⟩
    refine ⟨k, hnk, hφ, ?_⟩
    intro j _ _
    exact Cslib.Logic.Modal.Satisfies.true

@[scoped grind =, modal =]
theorem Satisfies.raw_always_iff
    (m : Model State Atom)
    (n a : ℕ) (φ : RawProposition Atom) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ φ.always] ↔
      ∀ k, n ≤ k → ⇓Modal[m.toModal,⟨k, n⟩ ⊨ φ] := by
  change
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ ¬(¬φ).eventually] ↔ _
  rw [Cslib.Logic.Modal.Satisfies.not_iff_not, Satisfies.raw_eventually_iff]
  constructor
  · intro h k hnk
    by_contra hk
    apply h
    refine ⟨k, hnk, ?_⟩
    exact Cslib.Logic.Modal.Satisfies.not_iff_not.mpr hk
  · intro h hex
    rcases hex with ⟨k, hnk, hk⟩
    exact Cslib.Logic.Modal.Satisfies.not_iff_not.mp hk (h k hnk)

/-- Release holds when every future position either satisfies `ψ` or is preceded by a
position satisfying `φ`. The position satisfying `φ` must itself satisfy `ψ`. -/
@[scoped grind =, modal =]
theorem Satisfies.raw_release_iff
    (m : Model State Atom)
    (n a : ℕ) (φ ψ : RawProposition Atom) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ φ.release ψ] ↔
      ∀ k, n ≤ k →
        ⇓Modal[m.toModal,⟨k, n⟩ ⊨ ψ] ∨
        ∃ j, n ≤ j ∧ j < k ∧ ⇓Modal[m.toModal,⟨j, n⟩ ⊨ φ] := by
  change ⇓Modal[m.toModal,⟨n, a⟩ ⊨ ¬(¬φ).until (¬ψ)] ↔ _
  simp only [Modal.Satisfies.not_iff_not, Satisfies.raw_until_iff]
  push Not
  simp only [or_iff_not_imp_left]

/-- Standard LTL formulas cannot observe the auxiliary anchor, including under nested untils. -/
theorem Satisfies.anchor_iff_of_isLTL
    (m : Model State Atom)
    {φ : RawProposition Atom} (hφ : IsLTL φ) (n a b : ℕ) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ φ] ↔
      ⇓Modal[m.toModal,⟨n, b⟩ ⊨ φ] := by
  induction hφ generalizing n a b with
  | atom => rfl
  | false => rfl
  | not _ ih => simp only [Modal.Satisfies.not_iff_not, ih n a b]
  | or _ _ ihφ ihψ => simp only [Modal.Satisfies.or_iff_or, ihφ n a b, ihψ n a b]
  | next _ ih => simpa only [Satisfies.raw_next_iff] using ih (n + 1) a b
  | «until» => rw [Satisfies.raw_until_iff, Satisfies.raw_until_iff]

/-- LTL propositions cannot observe the auxiliary anchor. -/
theorem Satisfies.anchor_iff (m : Model State Atom) (φ : Proposition Atom) (n a b : ℕ) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ φ.val] ↔ ⇓Modal[m.toModal,⟨n, b⟩ ⊨ φ.val] :=
  Satisfies.anchor_iff_of_isLTL m φ.property n a b

/-! ## Semantics of LTL propositions -/

/-- Next advances the current position by one. -/
@[scoped grind =, modal =]
theorem Satisfies.next_iff (m : Model State Atom) (n a : ℕ) (φ : Proposition Atom) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ φ.next.val] ↔
      ⇓Modal[m.toModal,⟨n + 1, a⟩ ⊨ φ.val] :=
  Satisfies.raw_next_iff m n a φ.val

/-- Standard until semantics with a fixed anchor for all subformulas. -/
theorem Satisfies.until_iff
    (m : Model State Atom)
    (n a : ℕ) (φ ψ : Proposition Atom) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ (φ.until ψ).val] ↔
      ∃ k, n ≤ k ∧
        ⇓Modal[m.toModal,⟨k, a⟩ ⊨ ψ.val] ∧
        ∀ j, n ≤ j → j < k → ⇓Modal[m.toModal,⟨j, a⟩ ⊨ φ.val] := by
  simp only [Satisfies.raw_until_iff, Satisfies.anchor_iff m φ _ n a,
    Satisfies.anchor_iff m ψ _ n a]

/-- Standard eventually semantics with a fixed anchor. -/
theorem Satisfies.eventually_iff
    (m : Model State Atom)
    (n a : ℕ) (φ : Proposition Atom) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ φ.eventually.val] ↔
      ∃ k, n ≤ k ∧ ⇓Modal[m.toModal,⟨k, a⟩ ⊨ φ.val] := by
  simp only [Satisfies.raw_eventually_iff, Satisfies.anchor_iff m φ _ n a]

/-- Standard always semantics with a fixed anchor. -/
theorem Satisfies.always_iff
    (m : Model State Atom)
    (n a : ℕ) (φ : Proposition Atom) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ φ.always.val] ↔
      ∀ k, n ≤ k → ⇓Modal[m.toModal,⟨k, a⟩ ⊨ φ.val] := by
  simp only [Satisfies.raw_always_iff, Satisfies.anchor_iff m φ _ n a]

/-- Standard release semantics with a fixed anchor. -/
theorem Satisfies.release_iff
    (m : Model State Atom)
    (n a : ℕ) (φ ψ : Proposition Atom) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ (φ.release ψ).val] ↔
      ∀ k, n ≤ k →
        ⇓Modal[m.toModal,⟨k, a⟩ ⊨ ψ.val] ∨
        ∃ j, n ≤ j ∧ j < k ∧ ⇓Modal[m.toModal,⟨j, a⟩ ⊨ φ.val] := by
  simp only [Satisfies.raw_release_iff, Satisfies.anchor_iff m φ _ n a,
    Satisfies.anchor_iff m ψ _ n a]

/-- Unfolding strong until by one step. -/
theorem Satisfies.until_unfold
    (m : Model State Atom)
    (n a : ℕ) (φ ψ : Proposition Atom) :
    ⇓Modal[m.toModal,⟨n, a⟩ ⊨ (φ.until ψ).val] ↔
      ⇓Modal[m.toModal,⟨n, a⟩ ⊨ (ψ ∨ (φ ∧ (φ.until ψ).next)).val] := by
  simp only [Proposition.val_or, Proposition.val_and, Modal.Satisfies.or_iff_or,
    Modal.Satisfies.and_iff_and, Satisfies.raw_next_iff,
    Satisfies.until_iff m _ a φ ψ]
  constructor
  · rintro ⟨k, hnk, hψk, hφk⟩
    by_cases h : n = k
    · subst k
      exact Or.inl hψk
    · exact Or.inr ⟨hφk n (by omega) (by omega),
        k, by omega, hψk, fun j hj hk => hφk j (by omega) hk⟩
  · rintro (hψn | ⟨hφn, k, hnk, hψk, hφk⟩)
    · exact ⟨n, Nat.le_refl n, hψn, by omega⟩
    · refine ⟨k, by omega, hψk, fun j hj hk => ?_⟩
      by_cases h : j = n
      · simpa only [h] using hφn
      · exact hφk j (by omega) hk

/-! ## Semantics at sequence positions -/

/-- The position API agrees with evaluation at any auxiliary anchor for standard LTL formulas. -/
theorem Satisfies.at_iff
    (m : Model State Atom)
    (φ : Proposition Atom) (n a : ℕ) :
    ⇓LTL[m,n ⊨ φ] ↔
      ⇓Modal[m.toModal,⟨n, a⟩ ⊨ φ.val] :=
  Satisfies.anchor_iff m φ n 0 a

/-- Atoms refer to the state at the chosen sequence position. -/
theorem Satisfies.at_atom_iff
    (m : Model State Atom) (n : ℕ) (p : Atom) :
    ⇓LTL[m,n ⊨ p] ↔ m.v (m.seq n) p := Iff.rfl

/-- Predicate atoms apply directly to the state at the chosen sequence position. -/
theorem Satisfies.at_predicate_iff (t : ωSequence State) (n : ℕ) (P : StateAtom State) :
    ⇓LTL[Model.ofTracePredicates t,n ⊨ P] ↔ P (t n) := Iff.rfl

/-- Falsity is never satisfied. -/
@[scoped grind =, modal =]
theorem Satisfies.at_false_iff (m : Model State Atom) (n : ℕ) :
    ⇓LTL[m,n ⊨ ⊥] ↔ False := Modal.Satisfies.false

/-- Truth is always satisfied. -/
@[scoped grind ., modal .]
theorem Satisfies.at_true (m : Model State Atom) (n : ℕ) :
    ⇓LTL[m,n ⊨ ⊤] := Modal.Satisfies.true

/-- Negation uses the generic modal semantics. -/
@[scoped grind =, modal =]
theorem Satisfies.at_not_iff (m : Model State Atom) (n : ℕ) (φ : Proposition Atom) :
    ⇓LTL[m,n ⊨ ¬φ] ↔ ¬⇓LTL[m,n ⊨ φ] := Modal.Satisfies.not_iff_not

/-- The `∨` connective uses the generic modal semantics. -/
@[scoped grind =, modal =]
theorem Satisfies.at_or_iff (m : Model State Atom) (n : ℕ) (φ ψ : Proposition Atom) :
    ⇓LTL[m,n ⊨ φ ∨ ψ] ↔ ⇓LTL[m,n ⊨ φ] ∨ ⇓LTL[m,n ⊨ ψ] :=
  Modal.Satisfies.or_iff_or

/-- The `∧` connective uses the generic modal semantics. -/
@[scoped grind =, modal =]
theorem Satisfies.at_and_iff (m : Model State Atom) (n : ℕ) (φ ψ : Proposition Atom) :
    ⇓LTL[m,n ⊨ φ ∧ ψ] ↔ ⇓LTL[m,n ⊨ φ] ∧ ⇓LTL[m,n ⊨ ψ] :=
  Modal.Satisfies.and_iff_and

/-- The `→` connective uses the generic modal semantics. -/
@[scoped grind =, modal =]
theorem Satisfies.at_imp_iff (m : Model State Atom) (n : ℕ) (φ ψ : Proposition Atom) :
    ⇓LTL[m,n ⊨ φ → ψ] ↔ (⇓LTL[m,n ⊨ φ] → ⇓LTL[m,n ⊨ ψ]) :=
  Modal.Satisfies.imp_iff_imp

/-- The `↔` connective uses the generic modal semantics. -/
theorem Satisfies.at_iff_iff (m : Model State Atom) (n : ℕ) (φ ψ : Proposition Atom) :
    ⇓LTL[m,n ⊨ φ ↔ ψ] ↔ (⇓LTL[m,n ⊨ φ] ↔ ⇓LTL[m,n ⊨ ψ]) :=
  Modal.Satisfies.iff_iff_iff

/-- Next advances the sequence position by one. -/
theorem Satisfies.at_next_iff
    (m : Model State Atom) (n : ℕ) (φ : Proposition Atom) :
    ⇓LTL[m,n ⊨ X φ] ↔
      ⇓LTL[m,n + 1 ⊨ φ] :=
  Satisfies.next_iff m n 0 φ

/-- Strong until has a future witness, with its left operand holding strictly before it. -/
theorem Satisfies.at_until_iff
    (m : Model State Atom)
    (n : ℕ) (φ ψ : Proposition Atom) :
    ⇓LTL[m,n ⊨ φ U ψ] ↔
      ∃ k, n ≤ k ∧ ⇓LTL[m,k ⊨ ψ] ∧
        ∀ j, n ≤ j → j < k → ⇓LTL[m,j ⊨ φ] :=
  Satisfies.until_iff m n 0 φ ψ

/-- Eventually holds at some position at or after the current one. -/
theorem Satisfies.at_eventually_iff
    (m : Model State Atom)
    (n : ℕ) (φ : Proposition Atom) :
    ⇓LTL[m,n ⊨ F φ] ↔
      ∃ k, n ≤ k ∧ ⇓LTL[m,k ⊨ φ] :=
  Satisfies.eventually_iff m n 0 φ

/-- Always holds at every position at or after the current one. -/
theorem Satisfies.at_always_iff
    (m : Model State Atom)
    (n : ℕ) (φ : Proposition Atom) :
    ⇓LTL[m,n ⊨ G φ] ↔
      ∀ k, n ≤ k → ⇓LTL[m,k ⊨ φ] :=
  Satisfies.always_iff m n 0 φ

/-- Release requires its right operand unless its left operand held at an earlier position. -/
theorem Satisfies.at_release_iff
    (m : Model State Atom)
    (n : ℕ) (φ ψ : Proposition Atom) :
    ⇓LTL[m,n ⊨ φ R ψ] ↔
      ∀ k, n ≤ k → ⇓LTL[m,k ⊨ ψ] ∨
        ∃ j, n ≤ j ∧ j < k ∧ ⇓LTL[m,j ⊨ φ] :=
  Satisfies.release_iff m n 0 φ ψ

/-- Unfold strong until without exposing the auxiliary anchor. -/
theorem Satisfies.at_until_unfold
    (m : Model State Atom)
    (n : ℕ) (φ ψ : Proposition Atom) :
    ⇓LTL[m,n ⊨ φ U ψ] ↔
      ⇓LTL[m,n ⊨ ψ ∨ (φ ∧ X (φ U ψ))] :=
  Satisfies.until_unfold m n 0 φ ψ

end Cslib.Logic.Modal.LTL
