/-
Copyright (c) 2026 Chris Henson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Henson
-/

module

public import Cslib.Foundations.RelationAlgebra.SearchCounting
public import Cslib.Foundations.RelationAlgebra.AtomRenaming
public import Cslib.Foundations.RelationAlgebra.SearchBundles
public import Cslib.Foundations.RelationAlgebra.SearchData
public import Mathlib.Tactic.FinCases

/-!
# Counting integral relation algebras of signature ⟨1, 0, 2⟩

Generated by `scripts/RelationAlgebra/count_lean.py`. The cycle basis and all atom
renamings are checked independently of the untrusted search. Normalized atomic
associativity equations cover every quadruple, including the identity cases.
The certificate propagates forced choices and counts settled families at once.
-/

@[expose] public section

namespace Cslib.RelationAlgebra.Catalogue.Counts.I1S0N2

set_option maxRecDepth 8192
set_option Elab.async false
set_option maxErrors 1

/-- Closed lookup data for representatives of the Peircean orbits. -/
noncomputable def cycleRepValuesTree : Search.LookupTree (Cycle 0 2) :=
  (.branch 6 (.branch 3 (.branch 1 (.leaf ((.inr (0, false), .inr (0, false), .inr (0, true))))
    (.branch 2 (.leaf ((.inr (1, false), .inr (1, false), .inr (1, true)))) (.leaf ((.inr (0,
    false), .inr (0, false), .inr (0, false)))))) (.branch 4 (.leaf ((.inr (0, false), .inr (0,
    false), .inr (1, false)))) (.branch 5 (.leaf ((.inr (0, false), .inr (0, false), .inr (1,
    true)))) (.leaf ((.inr (0, false), .inr (0, true), .inr (1, false))))))) (.branch 9
    (.branch 7 (.leaf ((.inr (0, false), .inr (1, false), .inr (0, false)))) (.branch 8 (.leaf
    ((.inr (0, false), .inr (1, false), .inr (1, false)))) (.leaf ((.inr (0, false), .inr (1,
    false), .inr (1, true)))))) (.branch 10 (.leaf ((.inr (0, false), .inr (1, true), .inr (1,
    false)))) (.branch 11 (.leaf ((.inr (0, false), .inr (1, true), .inr (1, true)))) (.leaf
    ((.inr (1, false), .inr (1, false), .inr (1, false))))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def cycleRepValues (i : ℕ) : Cycle 0 2 :=
  if Nat.blt i 12 then
    Search.LookupTree.get ((.inr (0, false), .inr (0, false), .inr (0, true))) cycleRepValuesTree i
  else (.inr (0, false), .inr (0, false), .inr (0, true))

/-- Representatives of the Peircean orbits, in the search's branching order. -/
noncomputable def cycleReps (i : Fin 12) : Cycle 0 2 := cycleRepValues i

/-- The basis meets every diversity-cycle orbit. -/
theorem cycleReps_cover : ∀ c : Cycle 0 2,
    ∃ i, (some c.1, some c.2.1, some c.2.2) ∈ cycleOrbit (cycleReps i) := by
  decide +kernel

/-- Different basis indices describe disjoint Peircean orbits. -/
theorem cycleReps_distinct : ∀ i l,
    (some (cycleReps i).1, some (cycleReps i).2.1, some (cycleReps i).2.2) ∈
      cycleOrbit (cycleReps l) ↔ i = l := by
  decide +kernel

/-- Images of one diversity atom under the enumerated renamings. -/
noncomputable def renameAtom1Tree : Search.LookupTree (DiversityAtom 0 2) :=
  (.branch 4 (.branch 2 (.branch 1 (.leaf (.inr (0, false))) (.leaf (.inr (0, false))))
    (.branch 3 (.leaf (.inr (0, true))) (.leaf (.inr (0, true))))) (.branch 6 (.branch 5 (.leaf
    (.inr (1, false))) (.leaf (.inr (1, true)))) (.branch 7 (.leaf (.inr (1, false))) (.leaf
    (.inr (1, true))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def renameAtom1 (i : ℕ) : DiversityAtom 0 2 :=
  if Nat.blt i 8 then
    Search.LookupTree.get (.inr (0, false)) renameAtom1Tree i
  else .inr (0, false)

/-- Images of one diversity atom under the enumerated renamings. -/
noncomputable def renameAtom2Tree : Search.LookupTree (DiversityAtom 0 2) :=
  (.branch 4 (.branch 2 (.branch 1 (.leaf (.inr (0, true))) (.leaf (.inr (0, true)))) (.branch
    3 (.leaf (.inr (0, false))) (.leaf (.inr (0, false))))) (.branch 6 (.branch 5 (.leaf (.inr
    (1, true))) (.leaf (.inr (1, false)))) (.branch 7 (.leaf (.inr (1, true))) (.leaf (.inr (1,
    false))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def renameAtom2 (i : ℕ) : DiversityAtom 0 2 :=
  if Nat.blt i 8 then
    Search.LookupTree.get (.inr (0, true)) renameAtom2Tree i
  else .inr (0, true)

/-- Images of one diversity atom under the enumerated renamings. -/
noncomputable def renameAtom3Tree : Search.LookupTree (DiversityAtom 0 2) :=
  (.branch 4 (.branch 2 (.branch 1 (.leaf (.inr (1, false))) (.leaf (.inr (1, true)))) (.branch
    3 (.leaf (.inr (1, false))) (.leaf (.inr (1, true))))) (.branch 6 (.branch 5 (.leaf (.inr
    (0, false))) (.leaf (.inr (0, false)))) (.branch 7 (.leaf (.inr (0, true))) (.leaf (.inr
    (0, true))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def renameAtom3 (i : ℕ) : DiversityAtom 0 2 :=
  if Nat.blt i 8 then
    Search.LookupTree.get (.inr (1, false)) renameAtom3Tree i
  else .inr (1, false)

/-- Images of one diversity atom under the enumerated renamings. -/
noncomputable def renameAtom4Tree : Search.LookupTree (DiversityAtom 0 2) :=
  (.branch 4 (.branch 2 (.branch 1 (.leaf (.inr (1, true))) (.leaf (.inr (1, false)))) (.branch
    3 (.leaf (.inr (1, true))) (.leaf (.inr (1, false))))) (.branch 6 (.branch 5 (.leaf (.inr
    (0, true))) (.leaf (.inr (0, true)))) (.branch 7 (.leaf (.inr (0, false))) (.leaf (.inr (0,
    false))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def renameAtom4 (i : ℕ) : DiversityAtom 0 2 :=
  if Nat.blt i 8 then
    Search.LookupTree.get (.inr (1, true)) renameAtom4Tree i
  else .inr (1, true)

/-- All converse-preserving diversity-atom permutations. -/
noncomputable def renameDiversity (p : Fin 8) : DiversityAtom 0 2 → DiversityAtom 0 2
  | .inr (0, false) => renameAtom1 p
  | .inr (0, true) => renameAtom2 p
  | .inr (1, false) => renameAtom3 p
  | .inr (1, true) => renameAtom4 p

/-- Extend the diversity permutation by fixing the identity. -/
noncomputable def rename (p : Fin 8) : Atom 0 2 → Atom 0 2 :=
  Option.map (renameDiversity p)

/-- The atom maps are injective and preserve identity and converse. -/
theorem rename_laws : ∀ p, Function.Injective (rename p) ∧ rename p none = none ∧
    ∀ x, rename p x.converse = (rename p x).converse := by
  decide +kernel

/-- Every possible atom renaming occurs in the finite list. -/
theorem renamings_exhaustive : ∀ f : Atom 0 2 → Atom 0 2,
    Function.Injective f → f none = none →
      (∀ x, f x.converse = (f x).converse) → ∃ p : Fin 8, f = rename p := by
  exact renamings_exhaustive_of_atomPermutations rename (by decide +kernel)

/-- Closed typed lookup data for the induced cycle permutations. -/
noncomputable def orbitActionValuesTree : Search.LookupTree (Fin 12) :=
  (.branch 48 (.branch 24 (.branch 12 (.branch 6 (.branch 3 (.branch 1 (.leaf (0)) (.branch 2
    (.leaf (1)) (.leaf (2)))) (.branch 4 (.leaf (3)) (.branch 5 (.leaf (4)) (.leaf (5)))))
    (.branch 9 (.branch 7 (.leaf (6)) (.branch 8 (.leaf (7)) (.leaf (8)))) (.branch 10 (.leaf
    (9)) (.branch 11 (.leaf (10)) (.leaf (11)))))) (.branch 18 (.branch 15 (.branch 13 (.leaf
    (0)) (.branch 14 (.leaf (1)) (.leaf (2)))) (.branch 16 (.leaf (4)) (.branch 17 (.leaf (3))
    (.leaf (5))))) (.branch 21 (.branch 19 (.leaf (6)) (.branch 20 (.leaf (10)) (.leaf (9))))
    (.branch 22 (.leaf (8)) (.branch 23 (.leaf (7)) (.leaf (11))))))) (.branch 36 (.branch 30
    (.branch 27 (.branch 25 (.leaf (0)) (.branch 26 (.leaf (1)) (.leaf (2)))) (.branch 28
    (.leaf (4)) (.branch 29 (.leaf (3)) (.leaf (6))))) (.branch 33 (.branch 31 (.leaf (5))
    (.branch 32 (.leaf (7)) (.leaf (9)))) (.branch 34 (.leaf (8)) (.branch 35 (.leaf (10))
    (.leaf (11)))))) (.branch 42 (.branch 39 (.branch 37 (.leaf (0)) (.branch 38 (.leaf (1))
    (.leaf (2)))) (.branch 40 (.leaf (3)) (.branch 41 (.leaf (4)) (.leaf (6))))) (.branch 45
    (.branch 43 (.leaf (5)) (.branch 44 (.leaf (10)) (.leaf (8)))) (.branch 46 (.leaf (9))
    (.branch 47 (.leaf (7)) (.leaf (11)))))))) (.branch 72 (.branch 60 (.branch 54 (.branch 51
    (.branch 49 (.leaf (1)) (.branch 50 (.leaf (0)) (.leaf (11)))) (.branch 52 (.leaf (9))
    (.branch 53 (.leaf (8)) (.leaf (7))))) (.branch 57 (.branch 55 (.leaf (10)) (.branch 56
    (.leaf (5)) (.leaf (4)))) (.branch 58 (.leaf (3)) (.branch 59 (.leaf (6)) (.leaf (2))))))
    (.branch 66 (.branch 63 (.branch 61 (.leaf (1)) (.branch 62 (.leaf (0)) (.leaf (11))))
    (.branch 64 (.leaf (8)) (.branch 65 (.leaf (9)) (.leaf (10))))) (.branch 69 (.branch 67
    (.leaf (7)) (.branch 68 (.leaf (5)) (.leaf (3)))) (.branch 70 (.leaf (4)) (.branch 71
    (.leaf (6)) (.leaf (2))))))) (.branch 84 (.branch 78 (.branch 75 (.branch 73 (.leaf (1))
    (.branch 74 (.leaf (0)) (.leaf (11)))) (.branch 76 (.leaf (8)) (.branch 77 (.leaf (9))
    (.leaf (7))))) (.branch 81 (.branch 79 (.leaf (10)) (.branch 80 (.leaf (6)) (.leaf (3))))
    (.branch 82 (.leaf (4)) (.branch 83 (.leaf (5)) (.leaf (2)))))) (.branch 90 (.branch 87
    (.branch 85 (.leaf (1)) (.branch 86 (.leaf (0)) (.leaf (11)))) (.branch 88 (.leaf (9))
    (.branch 89 (.leaf (8)) (.leaf (10))))) (.branch 93 (.branch 91 (.leaf (7)) (.branch 92
    (.leaf (6)) (.leaf (4)))) (.branch 94 (.leaf (3)) (.branch 95 (.leaf (5)) (.leaf (2)))))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def orbitActionValues (i : ℕ) : Fin 12 :=
  if Nat.blt i 96 then
    Search.LookupTree.get (0) orbitActionValuesTree i
  else 0

/-- The action of an atom renaming on the cycle basis. -/
noncomputable def orbitAction (p : Fin 8) (i : Fin 12) : Fin 12 :=
  orbitActionValues (p.val * 12 + i.val)

/-- The stored cycle action agrees with the actual atom maps. -/
theorem orbitAction_spec : ∀ p i,
    (some (renameDiversity p (cycleReps i).1),
      some (renameDiversity p (cycleReps i).2.1),
      some (renameDiversity p (cycleReps i).2.2)) ∈
        cycleOrbit (cycleReps (orbitAction p i)) := by
  decide +kernel

/-- Packed blocks for bounded numeric lookup. -/
noncomputable def slotValuesBlocksTree : Search.LookupTree (ℕ) :=
  (.branch 2 (.branch 1 (.leaf (85070612091872386754145177743375990785)) (.leaf
    (133091716878138822205640526293148898898))) (.branch 3 (.leaf
    (26390837275233322042988121032010331397)) (.leaf (68709266476499692914898282127351193))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def slotValuesBlocks (i : ℕ) : ℕ :=
  if Nat.blt i 4 then
    Search.LookupTree.get (0) slotValuesBlocksTree i
  else 0

/-- A bounded numeric table decoded from packed blocks. -/
noncomputable def slotValues (i : ℕ) : ℕ :=
  if Nat.blt i 125 then
    Code.field (slotValuesBlocks (Nat.shiftRight i 5)) (Nat.land i 31 * 4) 4
  else 0

/-- Numeric slots for every atom triple, including forced identity cycles. -/
noncomputable def slots (a b c : ℕ) : ℕ :=
  slotValues (Code.index 5 a b c)

/-- The slot representation agrees with cycle closure. -/
theorem slots_spec : CycleSlots cycleReps slots := by
  decide +kernel

/-- The distinct atomic associativity equations used by the search. -/
noncomputable def equationsTree : Search.LookupTree (Search.Equation) :=
  (.branch 17 (.branch 8 (.branch 4 (.branch 2 (.branch 1 (.leaf (⟨[4, 5, 40, 48], [4, 5, 72,
    80]⟩)) (.leaf (⟨[12, 33, 136, 528], [12, 65, 528, 1032]⟩))) (.branch 3 (.leaf (⟨[20, 33,
    264, 1040], [20, 65, 144, 264]⟩)) (.leaf (⟨[0], [1, 4, 8, 16]⟩)))) (.branch 6 (.branch 5
    (.leaf (⟨[12, 36, 160, 544], [17, 36, 272, 1032]⟩)) (.leaf (⟨[9, 36, 144, 520], [20, 36,
    288, 1056]⟩))) (.branch 7 (.leaf (⟨[9, 68, 520, 1040], [20, 68, 192, 320]⟩)) (.leaf (⟨[48,
    72, 128, 768], [129, 132, 2056, 2064]⟩))))) (.branch 12 (.branch 10 (.branch 9 (.leaf
    (⟨[10, 260, 513, 2064], [48, 80, 384, 1280]⟩)) (.leaf (⟨[12, 68, 576, 1088], [17, 68, 136,
    272]⟩))) (.branch 11 (.leaf (⟨[18, 257, 516, 2056], [40, 72, 640, 1536]⟩)) (.leaf (⟨[40,
    80, 768, 1024], [1025, 1028, 2056, 2064]⟩)))) (.branch 14 (.branch 13 (.leaf (⟨[12, 36,
    192, 576], [12, 68, 544, 1056]⟩)) (.leaf (⟨[20, 36, 320, 1088], [20, 68, 160, 288]⟩)))
    (.branch 15 (.leaf (⟨[0], [8, 32, 128, 512]⟩)) (.branch 16 (.leaf (⟨[24, 32, 384, 1536],
    [34, 260, 516, 2080]⟩)) (.leaf (⟨[0], [16, 32, 256, 1024]⟩))))))) (.branch 26 (.branch 21
    (.branch 19 (.branch 18 (.leaf (⟨[40, 48, 768, 1152], [72, 80, 768, 1152]⟩)) (.leaf (⟨[48,
    1280], [80, 384]⟩))) (.branch 20 (.leaf (⟨[8, 96, 512, 1152], [16, 96, 256, 1152]⟩)) (.leaf
    (⟨[24, 96, 384, 640], [24, 96, 1280, 1536]⟩)))) (.branch 23 (.branch 22 (.leaf (⟨[24, 64,
    640, 1280], [66, 260, 516, 2112]⟩)) (.leaf (⟨[144, 192, 2176, 2304], [288, 514, 520,
    2176]⟩))) (.branch 24 (.leaf (⟨[130, 320, 528, 2304], [288, 528, 1026, 2304]⟩)) (.branch 25
    (.leaf (⟨[0], [16, 64, 128, 256]⟩)) (.leaf (⟨[136, 160, 2176, 2560], [258, 272, 576,
    2176]⟩)))))) (.branch 30 (.branch 28 (.branch 27 (.leaf (⟨[144, 160, 2304, 3072], [1040,
    1088, 2176, 2304]⟩)) (.leaf (⟨[40, 640], [72, 1536]⟩))) (.branch 29 (.leaf (⟨[0], [8, 64,
    512, 1024]⟩)) (.leaf (⟨[136, 192, 2560, 3072], [1032, 1056, 2176, 2560]⟩)))) (.branch 32
    (.branch 31 (.leaf (⟨[320, 514, 520, 3072], [1040, 1056, 2304, 3072]⟩)) (.leaf (⟨[130, 264,
    544, 2560], [264, 576, 1026, 2560]⟩))) (.branch 33 (.leaf (⟨[258, 272, 544, 3072], [1032,
    1088, 2560, 3072]⟩)) (.branch 34 (.leaf (⟨[384, 640, 2048, 2050], [1280, 1536, 2048,
    2050]⟩)) (.leaf (⟨[0], [2, 256, 512, 2048]⟩))))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def equations (i : ℕ) : Search.Equation :=
  if Nat.blt i 35 then
    Search.LookupTree.get (⟨[], []⟩) equationsTree i
  else ⟨[], []⟩

/-- A source quadruple for each retained associativity equation. -/
noncomputable def sourceQuadsTree : Search.LookupTree (Code.Quadruple) :=
  (.branch 17 (.branch 8 (.branch 4 (.branch 2 (.branch 1 (.leaf ((1, 1, 1, 1))) (.leaf ((1, 1,
    1, 3)))) (.branch 3 (.leaf ((1, 1, 1, 4))) (.leaf ((1, 1, 2, 1))))) (.branch 6 (.branch 5
    (.leaf ((1, 1, 2, 3))) (.leaf ((1, 1, 2, 4)))) (.branch 7 (.leaf ((1, 1, 3, 1))) (.leaf
    ((1, 1, 3, 3)))))) (.branch 12 (.branch 10 (.branch 9 (.leaf ((1, 1, 3, 4))) (.leaf ((1, 1,
    4, 1)))) (.branch 11 (.leaf ((1, 1, 4, 3))) (.leaf ((1, 1, 4, 4))))) (.branch 14 (.branch
    13 (.leaf ((1, 2, 1, 3))) (.leaf ((1, 2, 1, 4)))) (.branch 15 (.leaf ((1, 2, 3, 3)))
    (.branch 16 (.leaf ((1, 2, 3, 4))) (.leaf ((1, 2, 4, 4)))))))) (.branch 26 (.branch 21
    (.branch 19 (.branch 18 (.leaf ((1, 3, 1, 3))) (.leaf ((1, 3, 1, 4)))) (.branch 20 (.leaf
    ((1, 3, 2, 3))) (.leaf ((1, 3, 2, 4))))) (.branch 23 (.branch 22 (.leaf ((1, 3, 3, 1)))
    (.leaf ((1, 3, 3, 3)))) (.branch 24 (.leaf ((1, 3, 3, 4))) (.branch 25 (.leaf ((1, 3, 4,
    1))) (.leaf ((1, 3, 4, 3))))))) (.branch 30 (.branch 28 (.branch 27 (.leaf ((1, 3, 4, 4)))
    (.leaf ((1, 4, 1, 3)))) (.branch 29 (.leaf ((1, 4, 3, 1))) (.leaf ((1, 4, 3, 3)))))
    (.branch 32 (.branch 31 (.leaf ((1, 4, 3, 4))) (.leaf ((1, 4, 4, 3)))) (.branch 33 (.leaf
    ((1, 4, 4, 4))) (.branch 34 (.leaf ((3, 3, 3, 3))) (.leaf ((3, 3, 4, 3)))))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def sourceQuads (i : ℕ) : Code.Quadruple :=
  if Nat.blt i 35 then
    Search.LookupTree.get ((0, 0, 0, 0)) sourceQuadsTree i
  else (0, 0, 0, 0)

/-- Packed blocks for bounded numeric lookup. -/
noncomputable def equationCoverValuesBlocksTree : Search.LookupTree (ℕ) :=
  (.branch 10 (.branch 5 (.branch 2 (.branch 1 (.leaf
    (3487278741881489313242105235115370231167975246924463618275)) (.leaf
    (3487278741881489313242105235115370231167975246924463618275))) (.branch 3 (.leaf
    (3487278741881489313242105235115370231167975246924463618275)) (.branch 4 (.leaf
    (3487278741881489313242105235115370231167975246924463618275)) (.leaf
    (198530216128621338314945409834705585226304973562868283619))))) (.branch 7 (.branch 6
    (.leaf (1230691588596976066188716747489288001094635867083824431331)) (.leaf
    (2463308251533592577792674812626090547512943548131049272197))) (.branch 8 (.leaf
    (3487278741877109579724571287601609550528568577936572954842)) (.branch 9 (.leaf
    (3433630392524150618334454002061262998973494457926253689059)) (.leaf
    (991620974760393327219475987621766453813865198000051467021)))))) (.branch 15 (.branch 12
    (.branch 11 (.leaf (3487130081223225899302271407242524657210152061008678506659)) (.leaf
    (3487278741881489284971523436752211844954705187798682319075))) (.branch 13 (.leaf
    (3456165459007969930897811213741791289343426680837555239139)) (.branch 14 (.leaf
    (1890416855263932589353024398910743414047240130301525861524)) (.leaf
    (3487278741697080966701109257312246548400001532869848479774))))) (.branch 17 (.branch 16
    (.leaf (3487278741881489313242083765154799924618964510750717277091)) (.leaf
    (2478513427480007515860953761167518086599712307621810551011))) (.branch 18 (.leaf
    (3473193227536817210347283048681083992843774204783805417686)) (.branch 19 (.leaf
    (1004635965678749351290160052810800396826141920783980443875)) (.leaf
    (2658464010705918654981047727711)))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def equationCoverValuesBlocks (i : ℕ) : ℕ :=
  if Nat.blt i 20 then
    Search.LookupTree.get (0) equationCoverValuesBlocksTree i
  else 0

/-- A bounded numeric table decoded from packed blocks. -/
noncomputable def equationCoverValues (i : ℕ) : ℕ :=
  if Nat.blt i 625 then
    Code.field (equationCoverValuesBlocks (Nat.shiftRight i 5)) (Nat.land i 31 * 6) 6
  else 35

/-- Map every atom quadruple to its retained equation, with a tautology sentinel. -/
noncomputable def equationCover (a b c d : ℕ) : ℕ :=
  equationCoverValues (((a * 5 + b) * 5 + c) * 5 + d)

/-- Every retained equation comes from atomic associativity. -/
theorem sources_checked :
    Search.sourcesCheck 5 35 slots equations sourceQuads = true := by
  decide +kernel

private noncomputable def equationPairCover (a b : ℕ) : Bool :=
  Code.allBelow (fun c => Code.allBelow (fun d =>
    let eqn := Search.compileEquation 5 slots (a, b, c, d)
    eqn.left.beq eqn.right ||
      (Nat.blt (equationCover a b c d) 35 &&
        (equations (equationCover a b c d)).same eqn)) 5) 5

private theorem equationPairCover_0_0 : equationPairCover 0 0 = true := by
  decide +kernel

private theorem equationPairCover_0_1 : equationPairCover 0 1 = true := by
  decide +kernel

private theorem equationPairCover_0_2 : equationPairCover 0 2 = true := by
  decide +kernel

private theorem equationPairCover_0_3 : equationPairCover 0 3 = true := by
  decide +kernel

private theorem equationPairCover_0_4 : equationPairCover 0 4 = true := by
  decide +kernel

private theorem equationPairCover_1_0 : equationPairCover 1 0 = true := by
  decide +kernel

private theorem equationPairCover_1_1 : equationPairCover 1 1 = true := by
  decide +kernel

private theorem equationPairCover_1_2 : equationPairCover 1 2 = true := by
  decide +kernel

private theorem equationPairCover_1_3 : equationPairCover 1 3 = true := by
  decide +kernel

private theorem equationPairCover_1_4 : equationPairCover 1 4 = true := by
  decide +kernel

private theorem equationPairCover_2_0 : equationPairCover 2 0 = true := by
  decide +kernel

private theorem equationPairCover_2_1 : equationPairCover 2 1 = true := by
  decide +kernel

private theorem equationPairCover_2_2 : equationPairCover 2 2 = true := by
  decide +kernel

private theorem equationPairCover_2_3 : equationPairCover 2 3 = true := by
  decide +kernel

private theorem equationPairCover_2_4 : equationPairCover 2 4 = true := by
  decide +kernel

private theorem equationPairCover_3_0 : equationPairCover 3 0 = true := by
  decide +kernel

private theorem equationPairCover_3_1 : equationPairCover 3 1 = true := by
  decide +kernel

private theorem equationPairCover_3_2 : equationPairCover 3 2 = true := by
  decide +kernel

private theorem equationPairCover_3_3 : equationPairCover 3 3 = true := by
  decide +kernel

private theorem equationPairCover_3_4 : equationPairCover 3 4 = true := by
  decide +kernel

private theorem equationPairCover_4_0 : equationPairCover 4 0 = true := by
  decide +kernel

private theorem equationPairCover_4_1 : equationPairCover 4 1 = true := by
  decide +kernel

private theorem equationPairCover_4_2 : equationPairCover 4 2 = true := by
  decide +kernel

private theorem equationPairCover_4_3 : equationPairCover 4 3 = true := by
  decide +kernel

private theorem equationPairCover_4_4 : equationPairCover 4 4 = true := by
  decide +kernel

private theorem equationPairCover_all : ∀ a b : Fin 5, equationPairCover a b = true := by
  intro a b
  fin_cases a <;> fin_cases b
  · exact equationPairCover_0_0
  · exact equationPairCover_0_1
  · exact equationPairCover_0_2
  · exact equationPairCover_0_3
  · exact equationPairCover_0_4
  · exact equationPairCover_1_0
  · exact equationPairCover_1_1
  · exact equationPairCover_1_2
  · exact equationPairCover_1_3
  · exact equationPairCover_1_4
  · exact equationPairCover_2_0
  · exact equationPairCover_2_1
  · exact equationPairCover_2_2
  · exact equationPairCover_2_3
  · exact equationPairCover_2_4
  · exact equationPairCover_3_0
  · exact equationPairCover_3_1
  · exact equationPairCover_3_2
  · exact equationPairCover_3_3
  · exact equationPairCover_3_4
  · exact equationPairCover_4_0
  · exact equationPairCover_4_1
  · exact equationPairCover_4_2
  · exact equationPairCover_4_3
  · exact equationPairCover_4_4

/-- The retained equations cover all associativity conditions, including identity cases. -/
theorem equations_cover_checked :
    Search.equationsCoverCheck 5 35 slots equations equationCover = true := by
  apply Code.allBelow_eq_true.mpr
  intro a ha
  apply Code.allBelow_eq_true.mpr
  intro b hb
  exact equationPairCover_all ⟨a, ha⟩ ⟨b, hb⟩

/-- All numeric cycle-variable permutations in one literal. -/
noncomputable def permutationCodes : ℕ :=
  (nat_lit% "5726328453606347812445967934691230431698661\
    035643218272564614084272894861180929118331524610969666656587447673303568")

/-- Numeric cycle permutations stored as packed, fixed-width fields. -/
noncomputable def permutations (p i : ℕ) : ℕ :=
  if Nat.blt p 8 && Nat.blt i 12 then
    Code.field permutationCodes ((p * 12 + i) * 4) 4
  else 0

/-- Numeric permutations implement the certified orbit action. -/
theorem permutations_eq : ∀ p : Fin 8, ∀ i : Fin 12,
    permutations p i = (orbitAction p i).val := by
  decide +kernel

/-- The finite constraint problem certified by this row. -/
noncomputable def problem : Search.Problem where
  «variables» := 12
  equationCount := 35
  equations := equations
  permutationCount := 8
  permutations := permutations

/-- Numeric permutations preserve the bounds on the cycle indices. -/
theorem permutations_bounded : problem.PermutationsBounded := by
  have h : ∀ p : Fin 8, ∀ i : Fin 12,
      permutations p i < 12 := by decide +kernel
  exact fun p hp i hi => h ⟨p, hp⟩ ⟨i, hi⟩

/-- The numeric search problem presents precisely this relation-algebra signature. -/
noncomputable def presentation : problem.Presentation 0 2 where
  reps := cycleReps
  cover := cycleReps_cover
  distinct := cycleReps_distinct
  slots := slots
  slots_spec := slots_spec
  renames := renameDiversity
  rename_laws := rename_laws
  renames_exhaustive := renamings_exhaustive
  permutations_bounded := permutations_bounded
  action_spec p i := by
    have h : (⟨permutations p i, permutations_bounded p p.isLt i i.isLt⟩ :
        Fin 12) = orbitAction p i := Fin.ext (permutations_eq p i)
    change _ ∈ cycleOrbit (cycleReps
      (⟨permutations p i, permutations_bounded p p.isLt i i.isLt⟩ :
        Fin 12))
    rw [h]
    exact orbitAction_spec p i
  sources := sourceQuads
  sources_spec := sources_checked
  equationCover := equationCover
  equationCover_spec := equations_cover_checked

/-- Packed blocks for bounded numeric lookup. -/
noncomputable def reasonCodesBlocksTree : Search.LookupTree (ℕ) :=
  (.branch 8 (.branch 4 (.branch 2 (.branch 1 (.leaf ((nat_lit% "41222\
    678278123945863008745952377060524728882884325627997464320265865407361740\
    064611819642504612672723678376147847960342853744141164969047164516016304\
    086531404777754351760892447280720672104243966366124015120019932719138327\
    945390155926706996314934621437218113837208226931400889976825957993939008"))) (.leaf
    ((nat_lit% "14510558737\
    518619091480188325206724452896754446141242848026604210287233543714820355\
    117449168868950678269609861260187307868237473463901288325043408712060806\
    796486982798679240205027745128632639100399359451933735440726396722498948\
    245101484808423015116301765595482969115398177430744298397348744503756292")))) (.branch 3
    (.leaf ((nat_lit% "28285369596\
    773063542888758151333900271868604470841620642684751466136965332828084915\
    948795263653048870751150618353370470093278773922799798038094079931597380\
    187193794397301536840226044253887190496426940776387856795755733297892570\
    909082837239758053852342310861070385646452135399841782220046291828211781"))) (.leaf
    ((nat_lit% "2166366328\
    815956560892584411335980196272152350183915712785825787341797455602211791\
    007649997225950958857067412362448641759405466825232503963020285402964603\
    601818679005399235833250398752744253107673990297881197517593066472130712\
    016731644556697943225226427457998749942716242237018316453327677165682887"))))) (.branch 6
    (.branch 5 (.leaf ((nat_lit% "6727424\
    152032060923738181180926684539849606770795086729124229963491454550084045\
    999371476082974854455569520698932932749199798884079849073614709377754151\
    213705922569639224466590771843285700464335146157846638673250343339341053\
    503705804290557596757842146466467833515918777464073917283559590584647753"))) (.leaf
    ((nat_lit% "410648\
    041929245211615940054687098974489469918842627417973073946183438896792585\
    886810337110107454300045417334759084454631497791966379309722948042743907\
    284787277884082017615816558818483819233995600579571749275490561098477934\
    144871689269739685109310156577838588405946948338587330848152541077111882")))) (.branch 7
    (.leaf ((nat_lit% "4986728344\
    473389393186306477326606198140963087514383111799387664272758338763911100\
    713028774605360228788322912181508053828387977445523515710338831506566572\
    754301571104522142979507055264951545231004195830609470057697985328631370\
    146540994562869469274042707521275691243940496025989853849090799909769805"))) (.leaf
    ((nat_lit% "3514316\
    157647310723108473525313536769206131965973880220084215283675750493978049\
    003158916296602132203285359737122421874299380906470741246738994387705338\
    555996818207057365476667919750405840868056365587295840243439714767653187\
    687254457916140109805740265240599542529916769740516072188818837580283985")))))) (.branch 12
    (.branch 10 (.branch 9 (.leaf ((nat_lit% "9158517452\
    182714425490059461476248790962349042349223525999673778338644927119067507\
    659670345859859674861377507442744089729465359573891530774544853966901649\
    802240906051278607749771725102818876581870546532101929560361038593737395\
    367927921505722560708400371172630068643012811452204857810387440991682644"))) (.leaf
    ((nat_lit% "5430420\
    308684309576903701151201327108485722951555182824066415667564965648963184\
    912117883268820108415172861903897919513399775708785499422628547755672650\
    754502463947552660737970878272464451435137170301091978538045220697632196\
    996487763766379661864584780672963737684321412401190078954508388578361431")))) (.branch 11
    (.leaf ((nat_lit% "2895796\
    304285455778568214323456061988425350145986602115131448929066249507676661\
    182644957238063977894822388231249012809726566476892989158956818382958024\
    412188796213034502336108443714957868043390272698409145224256552995812983\
    100800237182257822767375281554257300231861651224354160798620752923664473"))) (.leaf
    ((nat_lit% "15696571145\
    282984281985164504237824973143725594368562526825002796223972069289479550\
    413467081638754455294401892500419016774852632057016214661977507297184118\
    121121328749062135788434903442224163409520959324759274807847251690283295\
    498654752776625458558011902979672022625806210076918478420268932327960669"))))) (.branch 14
    (.branch 13 (.leaf ((nat_lit% "5111261\
    274550813332221762325625828037470581373772667289743314224507119910631951\
    011343549472710669274383964476786383226111021871951726489404942019019002\
    719999931842708507249240522991279274924859457285355629561195668165887586\
    083822414103783077898410947187227795342168219116186757342728773940840480"))) (.leaf
    ((nat_lit% "247406333\
    628825535969059620562977527710729484615189470914867151489788434306614471\
    688476384038745354975087946618878865836562756756416910025861280118220625\
    184848008521174061469008069925613930816545861265043454409140195108642222\
    552781491638701096392009574177879208736762781522981765493290514989973603")))) (.branch 15
    (.leaf ((nat_lit% "5414590799\
    378228068248438888905707667855886732266511550428679544835802278122295001\
    816667605289640896110799280642355784769820079161811248131311727325486101\
    915426719303020072203427634174570539842961463169286311039031776701332483\
    773837970747531343755333950118719578879324105338143706243237324339131493"))) (.branch 16
    (.leaf ((nat_lit% "5424808276\
    379602668401196567295904636846749737702955759716058386478779554531448816\
    879351443983589819963154926641696994999799966368244756227749644889950073\
    008603315516795923609818752444996830086032752328828817510249226050368874\
    423166051148349070455765539563205907381285775947889453187896516078994024"))) (.leaf
    ((nat_lit% "230334720967236706257\
    984252515526757405232706776545099186006650918829442493415038003302712965\
    184664557174894696239700098989003119732922467959130620480884760342099945"))))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def reasonCodesBlocks (i : ℕ) : ℕ :=
  if Nat.blt i 17 then
    Search.LookupTree.get (0) reasonCodesBlocksTree i
  else 0

/-- A bounded numeric table decoded from packed blocks. -/
noncomputable def reasonCodes (i : ℕ) : ℕ :=
  if Nat.blt i 530 then
    Code.field (reasonCodesBlocks (Nat.shiftRight i 5)) (Nat.land i 31 * 31) 31
  else 0

/-- Decode one cached reason without referring to its validity proof. -/
noncomputable def reasonData (i : ℕ) : Search.ReasonData :=
  let code := reasonCodes i
  ⟨Code.field code 0 6, Code.bitAt code 6,
    Code.field code 7 12, Code.field code 19 12⟩

/-- Shared sufficient subcubes for all contradiction and retirement steps. -/
noncomputable def reasons : Search.ReasonTable where
  size := 530
  lookup := reasonData

private theorem reasonBlock000_checked :
    reasons.checkBlock problem 256 0 = true := by
  decide +kernel

private theorem reasonBlock001_checked :
    reasons.checkBlock problem 256 1 = true := by
  decide +kernel

private theorem reasonBlock002_checked :
    reasons.checkBlock problem 256 2 = true := by
  decide +kernel

/-- Each reason is checked by the original partial-constraint evaluator. -/
theorem reasons_valid : reasons.Valid problem := by
  apply reasons.valid_of_blocks problem 256 (by decide)
  intro block hblock
  have h : ∀ i : Fin 3, reasons.checkBlock problem 256 i = true := by
    intro i
    fin_cases i
    · exact reasonBlock000_checked
    · exact reasonBlock001_checked
    · exact reasonBlock002_checked
  exact h ⟨block, hblock⟩

/-- Packed blocks for bounded numeric lookup. -/
noncomputable def bundleCodesBlocksTree : Search.LookupTree (ℕ) :=
  (.branch 3 (.branch 1 (.leaf ((nat_lit%
    "1600492659299437574099548928980612407753205290240414555030938709258142\
    226133834162547650335636310118381561537235657320327605519314827321621017\
    660725175029528971615462573146642312634709029109299553668330456873354041\
    179103394182111105522828436284490396823672631454944501597463510702609873\
    130499148032734921203858940851001614835279637658765487918680389395172255\
    675122014821413434785575566338903521596510323810195216529296499230062384\
    657790708212643615353806914166163438663409935593409536646674749450420271\
    562567783841848027440220906754985400718314175287761489416495297620613117\
    631409353660279594651036329766240531554056173932833097783817354914824193"))) (.branch 2
    (.leaf ((nat_lit% "330253982995418276046815998710238854798867125518523263409137842427\
    452441239042278685590847549279550953320924168525046484353420364536116690\
    511115875443840499680001563153809516170066090120004353991910243494464908\
    841887086043798714315226344585027206123890237729473322043643480812578904\
    313155527143600884684533570152221076102100432098520815359319555083944667\
    560070602635619652289924536584469804832144804767010654966929795653225069\
    716647540756235634437623653680549233910121376195070377110391951161240432\
    308555987972176449366751430167852148114869556692534434266444353475808905\
    620944116533754156713596185746443217485098126368795582816471869787736557"))) (.leaf
    ((nat_lit% "326533284273438884086575996895298295869481817771384478286521611141910\
    953822223825449269026524099366097835734503938669973065259929692690799015\
    999545155634431045085322221328697943861635599212845779088325984968107820\
    858016981885435075527516741346337264876025600693206032593291531599436307\
    904831897855963545523878574379070679270390306377145854235409676574005110\
    654846436152398211517504044825400523900413428971449476887555238711746226\
    606941282168640269110085535285172803774007304229910937309257171189891496\
    594545562249122411196534810738721346424082820971912541100585275596031892\
    882641642886933171419725670056481869095001559112549651660138438872530948"))))) (.branch 5
    (.branch 4 (.leaf ((nat_lit%
    "320267008894827640618905243093257414036547897924498974363141669913966\
    623449078009335857529143304610530657904484929179752595671078533539749356\
    216217471564373904562102640848110616775456997925135751093033719117905327\
    319835055206029462790537136240306471991858858350508002377804365467322133\
    121129071080271932271898342932161897553373051513881755440199402629281380\
    851137765752606927799379377910682126158036701517822881962622158979552631\
    308620620876535349497031928063026661824284455554707602662838714618082757\
    670854072021929432477192284529037057539542073234698834950695951479721573\
    817312431743402027304348031549544537058418470481496897442766416469036800"))) (.leaf
    ((nat_lit% "2480404283033389425074372618556342334011394413005434586812811125807377\
    433437795083676815755783376269052554900257914119805845353176860465796354\
    389040761047060168424009447397082233262367756895138531219299217081758360\
    766237588569853992163879689225515159648251890298264595695361003763972653\
    785756730792521154654936478699018316489221321446476895572913509411076939\
    987849784138840656976728514746636710238021627688404479101850469565586904\
    942670256537664002075916898715450010603064357241371143003452218676736339\
    379305994299719428501095102313300452428972718727465023514652783766843083\
    724006099210391606921574472623224943409249516816719291015269010538905600")))) (.branch 6
    (.leaf ((nat_lit% "327473521825458665145541878599827658752401212445633279205107113033495\
    308255286664733769945045747090803001123558339682225643284880322419435956\
    965692615915980194204826000062878284436861021417852260224999534436159562\
    325710832118448184466090166636193078425834820023409916310320690187089195\
    617139489504253824495222349341735812062976325967201859428220348842060683\
    428006018373693596229664986448660028846647662677077493142977444574152153\
    653135110371995565208592143605593440267969533391425562555160944108802795\
    883033216870304262484057981269222504199212147145275033244921799617689887\
    224806534969337673826907244490474901336994549918900083066938700421136384"))) (.leaf
    ((nat_lit% "29044735995205774\
    408609200750549714847073091188088159797577262469916031505407401991694492\
    713252091698305882545046265931159621986291336128072429381575538049548288"))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def bundleCodesBlocks (i : ℕ) : ℕ :=
  if Nat.blt i 7 then
    Search.LookupTree.get (0) bundleCodesBlocksTree i
  else 0

/-- A bounded numeric table decoded from packed blocks. -/
noncomputable def bundleCodes (i : ℕ) : ℕ :=
  if Nat.blt i 200 then
    Code.field (bundleCodesBlocks (Nat.shiftRight i 5)) (Nat.land i 31 * 67) 67
  else 0

/-- Packed blocks with an independent field width stored in each header. -/
noncomputable def bundleReasonCodesBlocksTree : Search.LookupTree (ℕ) :=
  (.branch 3 (.branch 1 (.leaf ((nat_lit% "415474100991348956841760057061574\
    710734936796253540961986400882419110345087604768388340124462261639436407\
    728437534779887454176228063177104810131236616340153906704281460477597829\
    124772686671855253102541620756865880995498613850587331508797395906009663\
    146505849762810759370101390243520916427226306524467039382335272989192483\
    939450674918098339900466185548640312602043940925957070299809591649581754\
    038417527377148601881094370972418573658848873596841994315797766677641714\
    381195974523871837855873991850750594765714464312507044009832922453918176\
    052590095895348555917500856866086205621752380846943923584875298236607733\
    831704570456199474573545444309279354336901774651806188599501353460626476\
    642251801535433547790506908108199525364152331332704495359312496399910326\
    307498191710715792065096885043312571441623944311004141166921469609757731\
    446546459599885410006346309926988731800727742472895580380418005865273657\
    480234845842577057658890204569049744698777577319025450693904091562571164\
    124349612285153371054330223840460220624677273233152837355864125185495569\
    291569528656697655436407327406319170354662203208119029174511360497410987\
    474942035132267029883492816596853019646062458143307754530829824782453427\
    191050954273732504510645658796665388460417837927825687964618352156718340\
    049870814720336702285145201321610684940187560033360084067856605054945828\
    050381235639624125728796891085786337857091202504900511566698849550336437\
    057841375092479303492007751172341760549192830085347824364988976771728807\
    073903780137694319641217454157625336078561131807751417428277758714715087\
    167764913949174013932610845924753238803427574455295529085867870643957664\
    874939997396632269274816658150442875086779022358232292710389840731385839\
    278284332295907103136319499906884571557977814553060634457543244248256778\
    546548478391123592024691480346487454932489318983192646194932736377941599\
    525653824215449340340058518640555884913176048489996553014624018513736832\
    263205893928483491366286277659772515430063449250149286143863039970025638\
    579645175570249186748694991036819795238612956493696558578210614360564428\
    161149384687965142291191450926034797669035472503256314382295044511977589\
    018331559994940478224356469879788133556484041597528290798101838189140810\
    350959475769519359475971082401884712790575670927416240705903045186863401\
    943173765655233080980095426351069391038509723937419315562347643493608394\
    617939799009786994535050324961651555169807055212231069973099792497804315\
    007180050555070491772911575377688783184148000439934621326958967910448267\
    180696089737835667375008309298687585764100628147606744502865180878657031\
    640359798683515455214041891698701695963374955443198095177494334194808560\
    421268621770973242828263160748130587695483302491616824538063827525174045"))) (.branch 2
    (.leaf ((nat_lit% "38460544342358450010561680662385397939150124070555436252\
    346031478048788997448370668485759453326198448751782020499759912682620552\
    186613483622755210038397667338416673037589022102603690227487984603397305\
    502091971836589947596670626994451002636772683724989445408476930540981379\
    109195085605390062485795844515494887623496009758277783758790925901472311\
    531301773951689340102321899539424574936018694984306148059696462755881650\
    522397537120139337646735989004395681211649761516887224906150735440600068\
    296336888473870995947308971964143978003535565296478142817586564220657096\
    115889188192572983752741995469802590849149503578747258973414048166622247\
    652723316885759673172748535278647799468454279491364128477342803486679842\
    472051454813950994958856159080319257808869717425888552106210160763979211\
    544757743263570437504072324901660298811262853822922765313052683419183130\
    739405691147693824919112134458597373865090202680700194085506616259215193\
    301603172307342010480547682714014130547221050862376147714538033941599303\
    625159678639940399728156827053445531681257091450715315547191708578239486\
    420009440048875512334039870145016944788100910118675474491958935582519770\
    208746171850519782691902033425693623928300793659219987462523489908953035\
    808508383897013720466274968845791088895628954945159116414222225964715545\
    166409560537311377686249205876290671043538611895215678733143020433347736\
    934330407329723911593937151171715406797147667589797769143607048876596388\
    594869328878536569438288217500894704554654890548743411766137044247547208\
    883793359038129048743491113984525422058461738004994768315337867597513447\
    023658465077075343782585845667969824674411136145759100661131603394434191\
    372349678480021652990093620944242507976153331256521513687752143599389573\
    277513966694481465314079347419093287091225133348099718701233576578679369\
    616475562579361755042848133099773527405923662603559607314887222779119818\
    600323934453160075160738874891763623053834435112304629323798856415924171\
    274679360723878173899982417223919997962172645631558345907618744574388828\
    301234994308180895479231763173006140787922425732805641535690885571191630\
    802120961941980038980573621713152628476097328870793109781983510834550203\
    240219613704074202918960593197060531859573322437263217439750813264150362\
    991524068919071873446388842010590634381557066644702633093463552122081636\
    286464878153117600117399948681488827128205661333272280154378709860802939\
    430510579946565311307401955530287656813517151823626281638772629381354645\
    260317189945129832736043580248006574325294373514016741389419110741840196\
    928569379743273688606267838311058364958348764253298209352188159248651026"))) (.leaf
    ((nat_lit% "787505371093012581682687130639549698771689266821613722498508326454\
    372998456686863872383661392999326164467180513605816920711474282764262738\
    020984507839567849274978126083219424521649348562308199514430358186820063\
    200682978246143426359521582102306292623350530343321942696476711413856092\
    584355876354095612211575882932659851964811712381050034143793672748577066\
    969419848788948467000938632194662005634064809249713332268952830659193653\
    029401008971651512341135202049470899803426833031776638745689080431000669\
    303964587386132480585370943498289788778163865079205688050552309093385513\
    402346526839932819507988691479551204529884699062775434906582634009013409\
    996370931277114376191204632680850394656027899995010028817903926107291939\
    654254118340860744819127659707657039047919891056876915664358700060615620\
    289315567774616968618103850128808153116051426410214016824744020141331812\
    363280071503532428516286009719633842399839305226024547542392091742007294\
    066175190538036201835469895687328804972436964770031581336907518566257767\
    708219506583369297776384799799283881442484681208824386065548493320742511\
    081574010099554818778041655476623750384129405872068688024525426617594138\
    105300000314239224523843677063493026577292788461843833589130488474313383\
    103590844696676152728059728691790781527821121323171195415752766762143414\
    508039305262720078654232008642880260221097962998334024587939077354790533\
    964444252151521863596165565493696895275016714758376940011033014358373756\
    804817558661043971244853785057825314219195299166319150127268829155016610\
    323856945226335995199733715139582959676071801043346707385223034615884478\
    315405582126218162977073517184860589903566765606737118467670028666389405\
    776056677060933394826273151829190168719748577708428126004491681380857721\
    925369962147893239862139798659311926330382658651498981776716927132043748\
    852319045111331435961613517445471837655063106662587748153421789001578109\
    024040654674852692533157761310568526069586599488148007685739475536052941"))))) (.branch 5
    (.branch 4 (.leaf ((nat_lit% "607628230757180\
    824027035781047505226978087341699347063202439096011971219794754753967740\
    560416000513454349022823886226117857605475315423551891578507004277482284\
    549572243367588364818644048426179492508719928943798715557098209590050232\
    550536772362054494612881592567320763071263441681240083550722384793181414\
    253228125271029293483914868669287897847145995431479837770805672163920090\
    125931308750544242737258707632876353044051494428863545369886529733040324\
    678045929676411387229556227269177143279524706458136807665004109400753981\
    716405206746579612856176520943592954048337822710747296906178265407376102\
    654573156281035584282252984449214896725965115262487629564489392092173575\
    502595861446133378163381374521795114778558037444416021247813159299153052\
    811104173982092111538761970261043482036426126710004550534732974031046870\
    853882274283597213627753553971454011001222166251829242084744624247883006\
    408227363097280860266821255208517641657571215683205885544729052459701244\
    485827699867736613858289076887791099429180471309813599624761431062018193\
    718890249387386507351258573221012521985241062322943273593844920299033202"))) (.leaf
    ((nat_lit% "59376400884949443\
    144966757410329636765870559295755293101057462358098116604163080626817145\
    565655577249225662769127867979984174319624177996401551852071920502971076\
    176467649821495839462747574009543756415301767550032211131035110591897010\
    378625033471695793443437291941365221278899281407047512543080150661322742\
    945767319434546032728152765582451695666827752502640968286321298151242738\
    522758535506268045517252592725977574565530142898694720924376329597641651\
    980071919772099407274347558399081585043859136997503105957724350390304879\
    523610775239487202368747257128806178716336159021148741934436018071190635\
    526584474469568217521175207774900640519683742866210579010375849695446118\
    330570390977228040654055753094435887958860207196015829015056015738511766\
    618426175685766055410224603934135056414527363807338812315738974985523284")))) (.branch 6
    (.leaf ((nat_lit% "16226420042333631707107075343070239018\
    128798335059209783251391570708084496654225657434574975471937234955327251\
    860093561884769663820878779944063019185584702665373576775660667932060358\
    602518004789356993539384997973557466719454948945647435116789051534327748\
    515879800120719161347743360185174859967911324752330506201963500588755260\
    294267676847281384622212063170521621016305238767303987486851454506108005\
    304068412502853944535434838517171215387569359983250499632218476251173949\
    716566130641389113073092312392022279134488320120445936459235675459668238\
    500275532346117842900575818735597314651848769217271018478786755384738880"))) (.leaf
    ((nat_lit% "573914973278140711101986305409229\
    880353580493286680422668990462729375559181219470712398749886305663387693"))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def bundleReasonCodesBlocks (i : ℕ) : ℕ :=
  if Nat.blt i 7 then
    Search.LookupTree.get (0) bundleReasonCodesBlocksTree i
  else 0

/-- Bounded lookup through the adaptive-width packed blocks. -/
noncomputable def bundleReasonCodes (i : ℕ) : ℕ :=
  if Nat.blt i 200 then
    let block := bundleReasonCodesBlocks (Nat.shiftRight i 5)
    let width := Code.field block 0 9
    Code.field block (9 + Nat.land i 31 * width) width
  else 0

/-- The positive reasons used to validate one cached retirement bundle. -/
noncomputable def bundleReasons (i : ℕ) : List ℕ :=
  let code := bundleReasonCodes i
  Search.decodeBundleIndices 10 (Code.field code 0 5)
    (Nat.shiftRight code 5)

/-- Decode the masks used by one retirement step. -/
noncomputable def bundleData (i : ℕ) : Search.BundleData :=
  let code := bundleCodes i
  ⟨Code.field code 0 43, Code.field code 43 12,
    Code.field code 55 12⟩

/-- Consecutive retirements certified by unions of independently checked reasons. -/
noncomputable def bundles : Search.BundleTable where
  size := 200
  lookup := bundleData
  reasons := bundleReasons

private theorem bundleBlock000_checked :
    bundles.checkBlock reasons 256 0 = true := by
  decide +kernel

/-- Every cached union is checked against its constituent positive reasons. -/
theorem bundles_valid : bundles.Valid reasons := by
  apply bundles.valid_of_blocks reasons 256 (by decide)
  intro block hblock
  have h : ∀ i : Fin 1, bundles.checkBlock reasons 256 i = true := by
    intro i
    fin_cases i
    · exact bundleBlock000_checked
  exact h ⟨block, hblock⟩

private noncomputable def certificateTree00000 : Counting.Certificate :=
  certificate_lit% "s 186 b 11 b 10 b 9 b 8 s 180 f 1 1 411 f 7 0 285 s 159 b 6 f 4 1 297 f \
    3 1 342 s 71 f 5 0 88 r 103 f 3 0 89 f 4 0 106 s 106 f 5 1 197 s 89 b 2 \
    s 0 f 0 1 27 s 52 a s 10 b 0 s 34 a s 51 a s 139 f 6 0 357 f 1 0 383 f 7 \
    0 402 s 184 f 3 1 242 f 5 0 270 s 166 f 4 0 306 s 66 f 2 0 32 f 0 0 51 s \
    3 a f 8 0 162 s 131 f 1 0 358 f 5 0 385 f 7 0 403 s 185 f 4 1 213 f 6 0 \
    220 s 145 f 3 0 272 s 58 f 0 0 33 f 2 0 53 s 1 r 418 s 140 b 9 b 8 f 4 0 \
    361 f 3 0 386 s 182 f 1 1 411 s 99 f 7 1 286 s 171 f 5 0 304 f 6 0 322 s \
    39 b 2 s 0 f 0 1 27 s 68 r 457 s 17 a s 172 f 7 1 404 s 127 b 6 f 2 1 \
    259 f 4 0 360 s 16 f 5 0 269 s 175 f 0 0 143 s 77 b 3 s 37 f 1 0 305 s \
    165 a s 47 f 1 1 302 s 168 a f 5 1 268 s 117 b 4 f 1 1 303 s 134 b 3 f 2 \
    1 35 s 80 f 0 0 142 s 6 a s 21 f 0 1 141 s 83 b 2 s 196 a s 195 a s 31 b \
    3 f 2 1 105 f 1 0 139 s 95 f 0 0 142 s 42 a s 61 b 2 f 0 1 90 f 1 1 104 \
    s 90 a s 94 b 1 f 0 1 140 s 108 a s 107 a s 130 f 7 1 405 s 143 b 8 r \
    421 s 146 b 6 f 2 1 258 s 15 b 5 s 188 b 4 f 3 0 57 s 85 f 1 0 271 s 40 \
    a s 55 f 3 1 36 s 76 a s 74 f 4 1 269 s 167 f 3 1 347 s 46 a b 5 f 2 1 \
    172 s 123 f 3 1 307 f 4 1 322 s 7 r 438 s 115 b 4 b 3 f 2 1 35 s 9 b 1 b \
    0 s 34 a s 51 a b 0 s 34 a s 51 a s 19 b 2 f 0 1 90 s 101 f 1 1 203 s 91 \
    r 458 s 93 a s 28 b 3 r 422 s 187 b 2 f 0 1 90 s 100 f 1 1 203 s 92 a s \
    93 a s 183 b 10 b 9 b 8 s 179 b 7 s 158 b 6 f 4 1 297 f 3 1 342 s 71 f 5 \
    1 92 s 102 r 218 s 154 b 5 f 3 1 197 f 4 0 202 r 213 s 125 b 4 s 144 b 3 \
    s 88 b 2 s 0 f 0 1 27 s 52 r 459 s 11 b 1 b 0 s 34 a s 51 a b 0 s 34 a s \
    51 a s 23 f 1 0 102 s 97 b 2 s 72 f 0 0 52 s 43 r 459 s 48 b 0 s 62 a s \
    64 a s 33 b 3 f 1 0 139 s 105 r 417 s 109 b 2 f 0 0 34 s 44 r 459 s 45 a \
    s 129 f 1 0 285 s 162 b 6 f 3 1 342 s 177 f 2 1 8 s 70 f 5 1 146 s 111 r \
    219 f 2 1 173 s 13 b 5 f 4 1 185 f 3 0 202 s 136 r 221 s 75 b 4 s 98 b 3 \
    s 103 b 0 s 34 a s 51 a s 49 b 0 s 62 a s 64 a s 63 b 3 s 105 r 437 s 50 \
    a s 138 f 6 1 362 f 1 0 383 s 156 f 4 0 384 f 7 0 233 f 5 1 273 s 173 f \
    2 0 107 s 73 f 0 1 55 f 3 1 73 s 18 r 459 s 132 b 8 f 1 0 358 f 5 1 387 \
    s 135 f 3 0 359 s 181 f 7 0 334 s 178 f 2 0 145 f 6 1 174 s 119 f 0 1 37 \
    s 78 f 4 1 110 s 26 r 418 s 137 b 7 b 6 b 5 f 2 0 108 f 4 0 125 f 0 0 \
    144 f 3 1 161 s 112 f 1 1 308 s 2 r 56 f 2 1 174 s 120 f 4 0 230 s 150 r \
    257 s 155 b 5 f 2 1 175 s 121 f 3 1 204 f 4 0 232 s 149 r 332 s 113 b 4 \
    f 2 1 38 s 79 f 3 1 91 r 107 s 29 b 3 f 2 1 54 s 86 r 145 s 67 b 2 r 459 \
    s 189 a f 4 1 233 s 160 f 3 1 334 s 56 f 5 1 234 s 151 f 6 1 331 s 24 b \
    2 r 459 s 189 a s 141 b 9 b 8 b 7 s 157 f 1 0 287 s 163 r 419 s 128 b 6 \
    r 460 s 153 b 5 f 2 1 172 s 124 f 4 0 231 s 148 f 3 0 333 s 4 f 0 0 6 s \
    35 r 436 s 118 b 4 s 144 b 3 f 2 1 35 s 8 b 1 s 161 b 0 s 38 a s 53 a s \
    169 b 0 s 34 r 461 s 54 a s 22 f 1 0 102 s 96 b 2 f 0 1 58 s 65 r 459 s \
    82 b 0 s 62 a s 64 a s 32 b 3 f 1 0 139 s 104 r 420 s 59 b 2 r 459 s 190 \
    b 1 s 164 a s 169 a s 170 b 7 f 4 1 235 f 5 1 273 r 306 s 126 b 6 f 2 1 \
    259 s 16 r 460 s 153 b 5 f 2 1 172 s 122 f 3 0 333 s 4 f 0 0 7 s 69 f 4 \
    0 36 s 36 r 450 s 116 b 4 b 3 f 2 1 35 s 80 f 0 0 142 s 5 r 462 s 20 b 2 \
    f 0 1 55 s 87 f 1 1 109 s 84 r 459 s 81 b 1 b 0 s 197 a s 198 a b 0 r \
    479 s 199 a s 30 b 3 f 1 0 139 s 176 f 0 0 142 s 41 b 2 r 459 s 191 a s \
    60 b 2 r 459 s 190 a s 133 b 8 r 421 s 142 b 7 f 4 1 235 s 174 f 3 1 335 \
    s 57 f 6 1 236 s 152 f 5 1 332 s 25 r 419 s 147 b 6 f 2 1 258 s 14 r 460 \
    s 153 b 5 f 2 1 172 s 12 r 438 s 114 b 4 r 463 s 27 b 3 r 422 s 110 b 2 \
    r 459 b 1 b 0 s 192 a s 193 a b 0 r 464 s 194 a"
    []

private noncomputable def chunk00000State : Counting.ActiveSearch.State :=
  ⟨⟨0, 0⟩, 8796093022207⟩

private noncomputable def chunk00000Data :
    Counting.CountData Counting.ActiveSearch.State :=
  ⟨chunk00000State, 83⟩

private noncomputable def chunk00000References :
    ℕ → Option (Counting.CountData Counting.ActiveSearch.State) :=
  fun _ => none

private theorem chunk00000_checked :
    problem.checkBundleDataChunk reasons bundles
      chunk00000References chunk00000State
      certificateTree00000 = some 83 := by
  decide +kernel

private theorem chunk00000References_valid :
    Counting.ReferencesValid
      (Counting.ActiveSearch.modelCount problem.variables problem.constraints)
      chunk00000References := by
  intro index data h
  unfold chunk00000References at h
  exact False.elim (Option.some_ne_none data h.symm)

private theorem chunk00000_count :
    Counting.ActiveSearch.modelCount problem.variables problem.constraints
      chunk00000State = 83 :=
  problem.checkBundleDataChunk_sound permutations_bounded reasons reasons_valid
    bundles bundles_valid
    chunk00000References chunk00000References_valid chunk00000State
    certificateTree00000 83
    chunk00000_checked

/-- Independent fragment checks prove the complete initial model count. -/
theorem certified_count :
    Counting.ActiveSearch.modelCount problem.variables problem.constraints
      (Counting.ActiveSearch.initial problem.constraints) = 83 :=
  chunk00000_count

/-- The exact number of isomorphism classes with this atom signature. -/
theorem count : isomorphismClassCount 0 2 = 83 :=
  presentation.count_eq_of_initial 83 certified_count

end Cslib.RelationAlgebra.Catalogue.Counts.I1S0N2
