/-
Copyright (c) 2026 Chris Henson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Henson
-/

module

public import Cslib.Foundations.RelationAlgebra.SearchCounting
public import Cslib.Foundations.RelationAlgebra.AtomRenaming
public import Cslib.Foundations.RelationAlgebra.SearchBundles
public import Cslib.Foundations.RelationAlgebra.SearchData
public import Mathlib.Tactic.FinCases

/-!
# Counting integral relation algebras of signature ⟨1, 2, 1⟩

Generated by `scripts/RelationAlgebra/count_lean.py`. The cycle basis and all atom
renamings are checked independently of the untrusted search. Normalized atomic
associativity equations cover every quadruple, including the identity cases.
The certificate propagates forced choices and counts settled families at once.
-/

@[expose] public section

namespace Cslib.RelationAlgebra.Catalogue.Counts.I1S2N1

set_option maxRecDepth 8192
set_option Elab.async false
set_option maxErrors 1

/-- Closed lookup data for representatives of the Peircean orbits. -/
noncomputable def cycleRepValuesTree : Search.LookupTree (Cycle 2 1) :=
  (.branch 8 (.branch 4 (.branch 2 (.branch 1 (.leaf ((.inl 0, .inl 0, .inl 0))) (.leaf ((.inl
    1, .inl 1, .inl 1)))) (.branch 3 (.leaf ((.inr (0, false), .inr (0, false), .inr (0,
    true)))) (.leaf ((.inl 0, .inl 0, .inl 1))))) (.branch 6 (.branch 5 (.leaf ((.inl 0, .inl
    1, .inl 1))) (.leaf ((.inl 0, .inr (0, true), .inr (0, true))))) (.branch 7 (.leaf ((.inl
    1, .inr (0, true), .inr (0, true)))) (.leaf ((.inl 0, .inr (0, false), .inr (0,
    false))))))) (.branch 12 (.branch 10 (.branch 9 (.leaf ((.inl 1, .inr (0, false), .inr (0,
    false)))) (.leaf ((.inl 0, .inl 0, .inr (0, false))))) (.branch 11 (.leaf ((.inl 0, .inl 1,
    .inr (0, false)))) (.leaf ((.inl 0, .inl 1, .inr (0, true)))))) (.branch 14 (.branch 13
    (.leaf ((.inl 0, .inr (0, false), .inr (0, true)))) (.leaf ((.inl 1, .inl 1, .inr (0,
    false))))) (.branch 15 (.leaf ((.inl 1, .inr (0, false), .inr (0, true)))) (.leaf ((.inr
    (0, false), .inr (0, false), .inr (0, false))))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def cycleRepValues (i : ℕ) : Cycle 2 1 :=
  if Nat.blt i 16 then
    Search.LookupTree.get ((.inl 0, .inl 0, .inl 0)) cycleRepValuesTree i
  else (.inl 0, .inl 0, .inl 0)

/-- Representatives of the Peircean orbits, in the search's branching order. -/
noncomputable def cycleReps (i : Fin 16) : Cycle 2 1 := cycleRepValues i

/-- The basis meets every diversity-cycle orbit. -/
theorem cycleReps_cover : ∀ c : Cycle 2 1,
    ∃ i, (some c.1, some c.2.1, some c.2.2) ∈ cycleOrbit (cycleReps i) := by
  decide +kernel

/-- Different basis indices describe disjoint Peircean orbits. -/
theorem cycleReps_distinct : ∀ i l,
    (some (cycleReps i).1, some (cycleReps i).2.1, some (cycleReps i).2.2) ∈
      cycleOrbit (cycleReps l) ↔ i = l := by
  decide +kernel

/-- Images of one diversity atom under the enumerated renamings. -/
noncomputable def renameAtom1Tree : Search.LookupTree (DiversityAtom 2 1) :=
  (.branch 2 (.branch 1 (.leaf (.inl 0)) (.leaf (.inl 0))) (.branch 3 (.leaf (.inl 1)) (.leaf
    (.inl 1))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def renameAtom1 (i : ℕ) : DiversityAtom 2 1 :=
  if Nat.blt i 4 then
    Search.LookupTree.get (.inl 0) renameAtom1Tree i
  else .inl 0

/-- Images of one diversity atom under the enumerated renamings. -/
noncomputable def renameAtom2Tree : Search.LookupTree (DiversityAtom 2 1) :=
  (.branch 2 (.branch 1 (.leaf (.inl 1)) (.leaf (.inl 1))) (.branch 3 (.leaf (.inl 0)) (.leaf
    (.inl 0))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def renameAtom2 (i : ℕ) : DiversityAtom 2 1 :=
  if Nat.blt i 4 then
    Search.LookupTree.get (.inl 1) renameAtom2Tree i
  else .inl 1

/-- Images of one diversity atom under the enumerated renamings. -/
noncomputable def renameAtom3Tree : Search.LookupTree (DiversityAtom 2 1) :=
  (.branch 2 (.branch 1 (.leaf (.inr (0, false))) (.leaf (.inr (0, true)))) (.branch 3 (.leaf
    (.inr (0, false))) (.leaf (.inr (0, true)))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def renameAtom3 (i : ℕ) : DiversityAtom 2 1 :=
  if Nat.blt i 4 then
    Search.LookupTree.get (.inr (0, false)) renameAtom3Tree i
  else .inr (0, false)

/-- Images of one diversity atom under the enumerated renamings. -/
noncomputable def renameAtom4Tree : Search.LookupTree (DiversityAtom 2 1) :=
  (.branch 2 (.branch 1 (.leaf (.inr (0, true))) (.leaf (.inr (0, false)))) (.branch 3 (.leaf
    (.inr (0, true))) (.leaf (.inr (0, false)))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def renameAtom4 (i : ℕ) : DiversityAtom 2 1 :=
  if Nat.blt i 4 then
    Search.LookupTree.get (.inr (0, true)) renameAtom4Tree i
  else .inr (0, true)

/-- All converse-preserving diversity-atom permutations. -/
noncomputable def renameDiversity (p : Fin 4) : DiversityAtom 2 1 → DiversityAtom 2 1
  | .inl 0 => renameAtom1 p
  | .inl 1 => renameAtom2 p
  | .inr (0, false) => renameAtom3 p
  | .inr (0, true) => renameAtom4 p

/-- Extend the diversity permutation by fixing the identity. -/
noncomputable def rename (p : Fin 4) : Atom 2 1 → Atom 2 1 :=
  Option.map (renameDiversity p)

/-- The atom maps are injective and preserve identity and converse. -/
theorem rename_laws : ∀ p, Function.Injective (rename p) ∧ rename p none = none ∧
    ∀ x, rename p x.converse = (rename p x).converse := by
  decide +kernel

/-- Every possible atom renaming occurs in the finite list. -/
theorem renamings_exhaustive : ∀ f : Atom 2 1 → Atom 2 1,
    Function.Injective f → f none = none →
      (∀ x, f x.converse = (f x).converse) → ∃ p : Fin 4, f = rename p := by
  exact renamings_exhaustive_of_atomPermutations rename (by decide +kernel)

/-- Closed typed lookup data for the induced cycle permutations. -/
noncomputable def orbitActionValuesTree : Search.LookupTree (Fin 16) :=
  (.branch 32 (.branch 16 (.branch 8 (.branch 4 (.branch 2 (.branch 1 (.leaf (0)) (.leaf (1)))
    (.branch 3 (.leaf (2)) (.leaf (3)))) (.branch 6 (.branch 5 (.leaf (4)) (.leaf (5)))
    (.branch 7 (.leaf (6)) (.leaf (7))))) (.branch 12 (.branch 10 (.branch 9 (.leaf (8)) (.leaf
    (9))) (.branch 11 (.leaf (10)) (.leaf (11)))) (.branch 14 (.branch 13 (.leaf (12)) (.leaf
    (13))) (.branch 15 (.leaf (14)) (.leaf (15)))))) (.branch 24 (.branch 20 (.branch 18
    (.branch 17 (.leaf (0)) (.leaf (1))) (.branch 19 (.leaf (2)) (.leaf (3)))) (.branch 22
    (.branch 21 (.leaf (4)) (.leaf (7))) (.branch 23 (.leaf (8)) (.leaf (5))))) (.branch 28
    (.branch 26 (.branch 25 (.leaf (6)) (.leaf (9))) (.branch 27 (.leaf (11)) (.leaf (10))))
    (.branch 30 (.branch 29 (.leaf (12)) (.leaf (13))) (.branch 31 (.leaf (14)) (.leaf
    (15))))))) (.branch 48 (.branch 40 (.branch 36 (.branch 34 (.branch 33 (.leaf (1)) (.leaf
    (0))) (.branch 35 (.leaf (2)) (.leaf (4)))) (.branch 38 (.branch 37 (.leaf (3)) (.leaf
    (6))) (.branch 39 (.leaf (5)) (.leaf (8))))) (.branch 44 (.branch 42 (.branch 41 (.leaf
    (7)) (.leaf (13))) (.branch 43 (.leaf (11)) (.leaf (10)))) (.branch 46 (.branch 45 (.leaf
    (14)) (.leaf (9))) (.branch 47 (.leaf (12)) (.leaf (15)))))) (.branch 56 (.branch 52
    (.branch 50 (.branch 49 (.leaf (1)) (.leaf (0))) (.branch 51 (.leaf (2)) (.leaf (4))))
    (.branch 54 (.branch 53 (.leaf (3)) (.leaf (8))) (.branch 55 (.leaf (7)) (.leaf (6)))))
    (.branch 60 (.branch 58 (.branch 57 (.leaf (5)) (.leaf (13))) (.branch 59 (.leaf (10))
    (.leaf (11)))) (.branch 62 (.branch 61 (.leaf (14)) (.leaf (9))) (.branch 63 (.leaf (12))
    (.leaf (15))))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def orbitActionValues (i : ℕ) : Fin 16 :=
  if Nat.blt i 64 then
    Search.LookupTree.get (0) orbitActionValuesTree i
  else 0

/-- The action of an atom renaming on the cycle basis. -/
noncomputable def orbitAction (p : Fin 4) (i : Fin 16) : Fin 16 :=
  orbitActionValues (p.val * 16 + i.val)

/-- The stored cycle action agrees with the actual atom maps. -/
theorem orbitAction_spec : ∀ p i,
    (some (renameDiversity p (cycleReps i).1),
      some (renameDiversity p (cycleReps i).2.1),
      some (renameDiversity p (cycleReps i).2.2)) ∈
        cycleOrbit (cycleReps (orbitAction p i)) := by
  decide +kernel

/-- Packed blocks for bounded numeric lookup. -/
noncomputable def slotValuesBlocksTree : Search.LookupTree (ℕ) :=
  (.branch 2 (.branch 1 (.leaf (92771101388346087949565297781057722432811433985)) (.leaf
    (689630178946192485080644133349095352355999722853))) (.branch 3 (.leaf
    (52162053497201878212460344690262261031988868111)) (.leaf
    (23891140639480438433594296242253849218827593))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def slotValuesBlocks (i : ℕ) : ℕ :=
  if Nat.blt i 4 then
    Search.LookupTree.get (0) slotValuesBlocksTree i
  else 0

/-- A bounded numeric table decoded from packed blocks. -/
noncomputable def slotValues (i : ℕ) : ℕ :=
  if Nat.blt i 125 then
    Code.field (slotValuesBlocks (Nat.shiftRight i 5)) (Nat.land i 31 * 5) 5
  else 0

/-- Numeric slots for every atom triple, including forced identity cycles. -/
noncomputable def slots (a b c : ℕ) : ℕ :=
  slotValues (Code.index 5 a b c)

/-- The slot representation agrees with cycle closure. -/
theorem slots_spec : CycleSlots cycleReps slots := by
  decide +kernel

/-- The distinct atomic associativity equations used by the search. -/
noncomputable def equationsTree : Search.LookupTree (Search.Equation) :=
  (.branch 16 (.branch 8 (.branch 4 (.branch 2 (.branch 1 (.leaf (⟨[513, 544, 2056, 4608],
    [513, 640, 1032, 4608]⟩)) (.leaf (⟨[0], [8, 16, 1024, 2048]⟩))) (.branch 3 (.leaf (⟨[520,
    1040, 1152, 6144], [576, 1025, 8200, 16896]⟩)) (.leaf (⟨[520, 2064, 2080, 5120], [768,
    2049, 8200, 16896]⟩)))) (.branch 6 (.branch 5 (.leaf (⟨[0], [128, 512, 1024, 4096]⟩))
    (.leaf (⟨[512, 3072, 4128, 4224], [516, 4097, 16392, 33280]⟩))) (.branch 7 (.leaf (⟨[0],
    [32, 512, 2048, 4096]⟩)) (.leaf (⟨[520, 1040, 2176, 5120], [520, 1056, 2064, 6144]⟩)))))
    (.branch 12 (.branch 10 (.branch 9 (.leaf (⟨[528, 1026, 8320, 12288], [1032, 1088, 8208,
    18432]⟩)) (.leaf (⟨[528, 2050, 8224, 12288], [2056, 2304, 8208, 17408]⟩))) (.branch 11
    (.leaf (⟨[1032, 2112, 8208, 17408], [1280, 2056, 8208, 18432]⟩)) (.leaf (⟨[136, 272, 33792,
    34816], [384, 2560, 9216, 20480]⟩)))) (.branch 14 (.branch 13 (.leaf (⟨[1028, 4104, 16400,
    34816], [2560, 4352, 10240, 16416]⟩)) (.leaf (⟨[1536, 4160, 9216, 16512], [2052, 4104,
    16400, 33792]⟩))) (.branch 15 (.leaf (⟨[40, 80, 33792, 34816], [96, 1536, 10240, 20480]⟩))
    (.leaf (⟨[512, 1024, 4224], [512, 2048, 4128]⟩)))))) (.branch 24 (.branch 20 (.branch 18
    (.branch 17 (.leaf (⟨[1536, 4160, 10240, 16416], [2560, 4352, 9216, 16512]⟩)) (.leaf
    (⟨[640, 1280, 32896, 36864], [4100, 4608, 17408, 32896]⟩))) (.branch 19 (.leaf (⟨[36, 4608,
    18432, 36864], [132, 4608, 17408, 36864]⟩)) (.leaf (⟨[544, 1088, 32896, 36864], [640, 2304,
    32800, 36864]⟩)))) (.branch 22 (.branch 21 (.leaf (⟨[544, 2112, 32800, 36864], [4100, 4608,
    18432, 32800]⟩)) (.leaf (⟨[1040, 8194, 8256, 24576], [2064, 8194, 8448, 24576]⟩))) (.branch
    23 (.leaf (⟨[0], [256, 2048, 8192, 16384]⟩)) (.leaf (⟨[3072, 8192, 16448, 16640], [4112,
    8196, 16386, 40960]⟩))))) (.branch 28 (.branch 26 (.branch 25 (.leaf (⟨[0], [64, 1024,
    8192, 16384]⟩)) (.leaf (⟨[1024, 8192, 16448], [2048, 8192, 16640]⟩))) (.branch 27 (.leaf
    (⟨[2176, 8448, 33024, 49152], [6144, 16388, 24576, 33024]⟩)) (.leaf (⟨[68, 5120, 24576,
    49152], [260, 6144, 24576, 49152]⟩)))) (.branch 30 (.branch 29 (.leaf (⟨[1152, 8448, 32832,
    49152], [2080, 8256, 33024, 49152]⟩)) (.leaf (⟨[1056, 8256, 32832, 49152], [5120, 16388,
    24576, 32832]⟩))) (.branch 31 (.leaf (⟨[4128, 16448, 32768, 32772], [4224, 16640, 32768,
    32772]⟩)) (.leaf (⟨[0], [4, 4096, 16384, 32768]⟩)))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def equations (i : ℕ) : Search.Equation :=
  if Nat.blt i 32 then
    Search.LookupTree.get (⟨[], []⟩) equationsTree i
  else ⟨[], []⟩

/-- A source quadruple for each retained associativity equation. -/
noncomputable def sourceQuadsTree : Search.LookupTree (Code.Quadruple) :=
  (.branch 16 (.branch 8 (.branch 4 (.branch 2 (.branch 1 (.leaf ((1, 1, 1, 3))) (.leaf ((1, 1,
    2, 2)))) (.branch 3 (.leaf ((1, 1, 2, 3))) (.leaf ((1, 1, 2, 4))))) (.branch 6 (.branch 5
    (.leaf ((1, 1, 3, 3))) (.leaf ((1, 1, 3, 4)))) (.branch 7 (.leaf ((1, 1, 4, 4))) (.leaf
    ((1, 2, 1, 3)))))) (.branch 12 (.branch 10 (.branch 9 (.leaf ((1, 2, 2, 3))) (.leaf ((1, 2,
    2, 4)))) (.branch 11 (.leaf ((1, 2, 3, 2))) (.leaf ((1, 2, 3, 3))))) (.branch 14 (.branch
    13 (.leaf ((1, 2, 3, 4))) (.leaf ((1, 2, 4, 3)))) (.branch 15 (.leaf ((1, 2, 4, 4))) (.leaf
    ((1, 3, 1, 4))))))) (.branch 24 (.branch 20 (.branch 18 (.branch 17 (.leaf ((1, 3, 2, 4)))
    (.leaf ((1, 3, 3, 3)))) (.branch 19 (.leaf ((1, 3, 3, 4))) (.leaf ((1, 3, 4, 4)))))
    (.branch 22 (.branch 21 (.leaf ((1, 4, 3, 4))) (.leaf ((2, 2, 2, 3)))) (.branch 23 (.leaf
    ((2, 2, 3, 3))) (.leaf ((2, 2, 3, 4)))))) (.branch 28 (.branch 26 (.branch 25 (.leaf ((2,
    2, 4, 4))) (.leaf ((2, 3, 2, 4)))) (.branch 27 (.leaf ((2, 3, 3, 3))) (.leaf ((2, 3, 3,
    4))))) (.branch 30 (.branch 29 (.leaf ((2, 3, 4, 4))) (.leaf ((2, 4, 3, 4)))) (.branch 31
    (.leaf ((3, 3, 3, 3))) (.leaf ((3, 3, 4, 3))))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def sourceQuads (i : ℕ) : Code.Quadruple :=
  if Nat.blt i 32 then
    Search.LookupTree.get ((0, 0, 0, 0)) sourceQuadsTree i
  else (0, 0, 0, 0)

/-- Packed blocks for bounded numeric lookup. -/
noncomputable def equationCoverValuesBlocksTree : Search.LookupTree (ℕ) :=
  (.branch 10 (.branch 5 (.branch 2 (.branch 1 (.leaf
    (3188369135434504514964210500676909925639291654330938165280)) (.leaf
    (3188369135434504514964210500676909925639291654330938165280))) (.branch 3 (.leaf
    (3188369135434504514964210500676909925639291654330938165280)) (.branch 4 (.leaf
    (3188369135434504514964210500676909925639291654330938165280)) (.leaf
    (778410433455689578848684204266823712314280189045639200))))) (.branch 7 (.branch 6 (.leaf
    (343497688704130701787935598260088098202063546911203792928)) (.leaf
    (1684320459803969329584271254916927202234817921272000856778))) (.branch 8 (.leaf
    (3188369135417058216217875794159073397649595344705678346259)) (.branch 9 (.leaf
    (3188357738736080460916435780730314706109072066097463822368)) (.leaf
    (2290054744473884612605268598114720524579756443718561694346)))))) (.branch 15 (.branch 12
    (.branch 11 (.leaf (3188271049218285419287680806424627517611806521731682488864)) (.leaf
    (3188369135434504498192946247758406166036460144809151170592))) (.branch 13 (.leaf
    (3157279458735388082780993410668381460935935876849463330848)) (.branch 14 (.leaf
    (3188367240666136424132342374806380175232923001126264583183)) (.leaf
    (3188369135250250531394027741078216816112081432517634295645))))) (.branch 17 (.branch 16
    (.leaf (3188369135434504514964189050840292920808819717049682800928)) (.leaf
    (1717173291666768862775050896244067972030169422848946472992))) (.branch 18 (.leaf
    (3182116714501174635166991848643471860109558869763416979473)) (.branch 19 (.leaf
    (1283477178138204652778186419232651700277527466150587402272)) (.leaf
    (2416986806243563633954570503250)))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def equationCoverValuesBlocks (i : ℕ) : ℕ :=
  if Nat.blt i 20 then
    Search.LookupTree.get (0) equationCoverValuesBlocksTree i
  else 0

/-- A bounded numeric table decoded from packed blocks. -/
noncomputable def equationCoverValues (i : ℕ) : ℕ :=
  if Nat.blt i 625 then
    Code.field (equationCoverValuesBlocks (Nat.shiftRight i 5)) (Nat.land i 31 * 6) 6
  else 32

/-- Map every atom quadruple to its retained equation, with a tautology sentinel. -/
noncomputable def equationCover (a b c d : ℕ) : ℕ :=
  equationCoverValues (((a * 5 + b) * 5 + c) * 5 + d)

/-- Every retained equation comes from atomic associativity. -/
theorem sources_checked :
    Search.sourcesCheck 5 32 slots equations sourceQuads = true := by
  decide +kernel

private noncomputable def equationPairCover (a b : ℕ) : Bool :=
  Code.allBelow (fun c => Code.allBelow (fun d =>
    let eqn := Search.compileEquation 5 slots (a, b, c, d)
    eqn.left.beq eqn.right ||
      (Nat.blt (equationCover a b c d) 32 &&
        (equations (equationCover a b c d)).same eqn)) 5) 5

private theorem equationPairCover_0_0 : equationPairCover 0 0 = true := by
  decide +kernel

private theorem equationPairCover_0_1 : equationPairCover 0 1 = true := by
  decide +kernel

private theorem equationPairCover_0_2 : equationPairCover 0 2 = true := by
  decide +kernel

private theorem equationPairCover_0_3 : equationPairCover 0 3 = true := by
  decide +kernel

private theorem equationPairCover_0_4 : equationPairCover 0 4 = true := by
  decide +kernel

private theorem equationPairCover_1_0 : equationPairCover 1 0 = true := by
  decide +kernel

private theorem equationPairCover_1_1 : equationPairCover 1 1 = true := by
  decide +kernel

private theorem equationPairCover_1_2 : equationPairCover 1 2 = true := by
  decide +kernel

private theorem equationPairCover_1_3 : equationPairCover 1 3 = true := by
  decide +kernel

private theorem equationPairCover_1_4 : equationPairCover 1 4 = true := by
  decide +kernel

private theorem equationPairCover_2_0 : equationPairCover 2 0 = true := by
  decide +kernel

private theorem equationPairCover_2_1 : equationPairCover 2 1 = true := by
  decide +kernel

private theorem equationPairCover_2_2 : equationPairCover 2 2 = true := by
  decide +kernel

private theorem equationPairCover_2_3 : equationPairCover 2 3 = true := by
  decide +kernel

private theorem equationPairCover_2_4 : equationPairCover 2 4 = true := by
  decide +kernel

private theorem equationPairCover_3_0 : equationPairCover 3 0 = true := by
  decide +kernel

private theorem equationPairCover_3_1 : equationPairCover 3 1 = true := by
  decide +kernel

private theorem equationPairCover_3_2 : equationPairCover 3 2 = true := by
  decide +kernel

private theorem equationPairCover_3_3 : equationPairCover 3 3 = true := by
  decide +kernel

private theorem equationPairCover_3_4 : equationPairCover 3 4 = true := by
  decide +kernel

private theorem equationPairCover_4_0 : equationPairCover 4 0 = true := by
  decide +kernel

private theorem equationPairCover_4_1 : equationPairCover 4 1 = true := by
  decide +kernel

private theorem equationPairCover_4_2 : equationPairCover 4 2 = true := by
  decide +kernel

private theorem equationPairCover_4_3 : equationPairCover 4 3 = true := by
  decide +kernel

private theorem equationPairCover_4_4 : equationPairCover 4 4 = true := by
  decide +kernel

private theorem equationPairCover_all : ∀ a b : Fin 5, equationPairCover a b = true := by
  intro a b
  fin_cases a <;> fin_cases b
  · exact equationPairCover_0_0
  · exact equationPairCover_0_1
  · exact equationPairCover_0_2
  · exact equationPairCover_0_3
  · exact equationPairCover_0_4
  · exact equationPairCover_1_0
  · exact equationPairCover_1_1
  · exact equationPairCover_1_2
  · exact equationPairCover_1_3
  · exact equationPairCover_1_4
  · exact equationPairCover_2_0
  · exact equationPairCover_2_1
  · exact equationPairCover_2_2
  · exact equationPairCover_2_3
  · exact equationPairCover_2_4
  · exact equationPairCover_3_0
  · exact equationPairCover_3_1
  · exact equationPairCover_3_2
  · exact equationPairCover_3_3
  · exact equationPairCover_3_4
  · exact equationPairCover_4_0
  · exact equationPairCover_4_1
  · exact equationPairCover_4_2
  · exact equationPairCover_4_3
  · exact equationPairCover_4_4

/-- The retained equations cover all associativity conditions, including identity cases. -/
theorem equations_cover_checked :
    Search.equationsCoverCheck 5 32 slots equations equationCover = true := by
  apply Code.allBelow_eq_true.mpr
  intro a ha
  apply Code.allBelow_eq_true.mpr
  intro b hb
  exact equationPairCover_all ⟨a, ha⟩ ⟨b, hb⟩

/-- All numeric cycle-variable permutations in one literal. -/
noncomputable def permutationCodes : ℕ :=
  114263289157408420128598490766137487755471132036366433336225976605968071668240

/-- Numeric cycle permutations stored as packed, fixed-width fields. -/
noncomputable def permutations (p i : ℕ) : ℕ :=
  if Nat.blt p 4 && Nat.blt i 16 then
    Code.field permutationCodes ((p * 16 + i) * 4) 4
  else 0

/-- Numeric permutations implement the certified orbit action. -/
theorem permutations_eq : ∀ p : Fin 4, ∀ i : Fin 16,
    permutations p i = (orbitAction p i).val := by
  decide +kernel

/-- The finite constraint problem certified by this row. -/
noncomputable def problem : Search.Problem where
  «variables» := 16
  equationCount := 32
  equations := equations
  permutationCount := 4
  permutations := permutations

/-- Numeric permutations preserve the bounds on the cycle indices. -/
theorem permutations_bounded : problem.PermutationsBounded := by
  have h : ∀ p : Fin 4, ∀ i : Fin 16,
      permutations p i < 16 := by decide +kernel
  exact fun p hp i hi => h ⟨p, hp⟩ ⟨i, hi⟩

/-- The numeric search problem presents precisely this relation-algebra signature. -/
noncomputable def presentation : problem.Presentation 2 1 where
  reps := cycleReps
  cover := cycleReps_cover
  distinct := cycleReps_distinct
  slots := slots
  slots_spec := slots_spec
  renames := renameDiversity
  rename_laws := rename_laws
  renames_exhaustive := renamings_exhaustive
  permutations_bounded := permutations_bounded
  action_spec p i := by
    have h : (⟨permutations p i, permutations_bounded p p.isLt i i.isLt⟩ :
        Fin 16) = orbitAction p i := Fin.ext (permutations_eq p i)
    change _ ∈ cycleOrbit (cycleReps
      (⟨permutations p i, permutations_bounded p p.isLt i i.isLt⟩ :
        Fin 16))
    rw [h]
    exact orbitAction_spec p i
  sources := sourceQuads
  sources_spec := sources_checked
  equationCover := equationCover
  equationCover_spec := equations_cover_checked

/-- Packed blocks for bounded numeric lookup. -/
noncomputable def reasonCodesBlocksTree : Search.LookupTree (ℕ) :=
  (.branch 12 (.branch 6 (.branch 3 (.branch 1 (.leaf ((nat_lit% "719419831341275\
    344882616497504739369355121620351756141938860666367515712881577540129149\
    477216124364454600837097237630955625192777417113572016434143309772272668\
    072915632010938032154051150226441829180211863518856802014416303951988359\
    959639248930388523050002450486771583861696758989005472980376187478817538\
    394374403350469210298188220082030666646462780896860744826328411988365312"))) (.branch 2
    (.leaf ((nat_lit% "876255617\
    936039663718368866031845296783299268762840128743475110910734965129083536\
    125427346500816060872965385256018802659025690566440847073126553066988061\
    425774228015849035626990443796095035415284287098087972144738886547103611\
    597366670262033706236219324983156215472685774225425836978131351308612966\
    950859385284750468805910245332585652928685939642942396873824105401418754"))) (.leaf
    ((nat_lit% "8090324897\
    599047333050872391045512491895660589906546246449943737129270822501186182\
    484969033530797307871211712225344069570938404412707732346476757726879352\
    757798925373207600524817974836469302975637747537486662178317968574865211\
    278247388679763855988050106035931664478773064427671968980023729178491126\
    958225844137598194314426831169238283676336132688776394665621942192834755"))))) (.branch 4
    (.leaf ((nat_lit% "1218160011546935\
    977972607152912700427026697668039476852918361273579670631053078354009861\
    253774184248749320529981830839063968244999489328723291212387433929231913\
    199728571600064543473954533464072625261026573486746299252064756605894728\
    211783538637664735689741569754905538717576011523736342499374696464736904\
    503872136785472358748330203411562615262650478233521918857420197427479621"))) (.branch 5
    (.leaf ((nat_lit% "1364295234125288\
    791199947938871150785333532219411056200948422224207458854168521094557079\
    499553596617879984263218558587981456550405906767073805568282884183112886\
    223754405663516311502091490789215228035732135023571849925522044992984871\
    667755476619900260192449399642726435322499293305762044587365439085692416\
    098294373438943767386408504140019760861258631855490849250143296455966728"))) (.leaf
    ((nat_lit% "3476217604\
    287381629428461779311977377973024810351185510185919880531089449715844482\
    788920109655500101040188435626585717330309946634371224278546478322655046\
    933730876053536198180231196740647049256178224369715233136055918867901050\
    525877030564290215607968285085161760407812389649434589791054471850447721\
    324706739949834022414652171785710075609800673775997425159870866757124105")))))) (.branch 9
    (.branch 7 (.leaf ((nat_lit% "10553741071\
    418309545408900622880592250825614202505055636980408471596815736569145205\
    731298599321693657951852272860139812784800157694154192605120016422397019\
    954644805012518503464923025035840567865870740671757429355855269896423375\
    529436826914652990954949795533949198546370157347821823318085091531019415\
    634414210385325497551670915793988933058893582348623484534377611335737418"))) (.branch 8
    (.leaf ((nat_lit% "23156059138\
    805378705728728244023579208484031937181955177693001160500118763093904400\
    027130923061677787971314969492574674040469653903719916125561212061792476\
    017995215338432791816249387737367513747268225627529964061260008840637046\
    847648971505294855809049062930642265901114741410890027960836043030083752\
    449170620893063888529218024797731693954427175893045617515729637594007627"))) (.leaf
    ((nat_lit% "56765235106\
    079817635734876373572378413716298992185566647386391457717420829434156873\
    115914565377714246229642642240311254283284074839228128449112337714304650\
    908642521502759126237123966940872971470999959106193378123960822129169479\
    520582051191874016075679750656881293680697609012087475884524054741197687\
    332433326373277741174586201693875448766021975713676357353129631717820492"))))) (.branch 10
    (.leaf ((nat_lit% "416504515406528\
    405745962794547927954748950399217026267633446942610048180353114125491803\
    596420468526833667719049000428674047554501288845271491339247755068491390\
    505074014509840899065218107050880707072517603490532092694918234826343785\
    142850979905957624086928880936774423108887535371570375230448438448031015\
    600651409367817397790469642812260261109544218496525209846523869530166286"))) (.branch 11
    (.leaf ((nat_lit% "2451688629513088\
    207982009238826969199975288271719297999618853571100313295616542437800098\
    686296909357888042863377519249743729442486460412421074019708907945722431\
    512442624722973244889635060196293788142693231243054236915774947394715865\
    883655654624379528829303231795177405294297345497727101630463927895287685\
    459332011096888489106467105705562826351907201323366730892267329325371407"))) (.leaf
    ((nat_lit% "2501380437653376\
    799763649587445152342220611420364238282681129566565286454218270111029829\
    345499179662986713779892768883756734797288463061631679005243047125081326\
    624774330048016752750037516654650945403718611598546879407366024206282495\
    441219907868449503515035612023720164247946087379881452796930690863895670\
    452333941676100283072808564349766935322542375924248656596919181296336913"))))))) (.branch
    18 (.branch 15 (.branch 13 (.leaf ((nat_lit% "7583791944\
    450053186213091515064691870974659159313356511426009553943506414971756991\
    183820853178880084259309169224614390296714320438072962937722506391899764\
    098156935249555077630275120287626968418191933104402934881527438373400925\
    221300478895396195809434973451335048886133597259542746312771232279350231\
    092331089910392711708396323398522624808815085949693095361799564296331283"))) (.branch 14
    (.leaf ((nat_lit% "3636416628415301\
    171177974174370749053102350763093798676901360000684243637886730032037095\
    572121624065375081678179352386448147010278554197749091957349823470430959\
    720462432057439173259878147623655690235952132363362758183299142526944182\
    545926572870069387965015445922185858855373290344595708239033312332893228\
    944750944299268088320896648191948853029028864690354552856247863863418964"))) (.leaf
    ((nat_lit% "1240047586864728\
    001993547980087404283164955611746601791097703568918204766751724249295131\
    431549846703936987590863067024632035704579126184234867450010549232039281\
    578419321871360665470503028889510971806522548885559626668946675834005191\
    007278592759291421530427750598515594896899924919148178709243584082337653\
    816025310914489993504194707737305300084065225998461539762891095781933079"))))) (.branch 16
    (.leaf ((nat_lit% "7010611078\
    494639370873110871650393721757192961873255601631187780770767424200506590\
    864637174060209981647981775591358046016897033311725279359525858434852003\
    804378833123020671104517252770025150156549138263871518337751756942596568\
    068538772736971797775353305017173986094877640553030973230320694838283673\
    119617276101017623135769550298079055815816692731938474354949887401656346"))) (.branch 17
    (.leaf ((nat_lit% "1292103429912604\
    267790994516098017684134983081490737387846520459808702417210592320162828\
    207949441000722448920410038586916227685221041230919426565590822418969346\
    170335990491645881825053550756689901568614424038152214190277229711400668\
    342886407962261346017485349956768418234110919246121064664113281739752559\
    057035020254277122694838658384585851504265329273484566192857259711529051"))) (.leaf
    ((nat_lit% "262680368307134\
    458041449849289654190368962179823326794010050431728623277994176455122291\
    551624812837153661905609581771677488571775981978259595797426900863571623\
    791534909424376160904105721877698110067073209830405282755538821027156009\
    068679122873728273833614797040495727279182627110828574088390483020432828\
    182972693415016900399204665076563242391784097714282416007923767971938397")))))) (.branch 21
    (.branch 19 (.leaf ((nat_lit% "871483537950135\
    468679299931169811163965015795093558109723862403294549177396933839196609\
    024158982803810014186594661293127480028850563689905673419313970644417275\
    408006780769456639138818243925038422632764877509906958665182678280443764\
    799220127829675219985634455453745014696922850737967538834954202565921985\
    264778444437693475850191480751183691729515222333918011526505463159984225"))) (.branch 20
    (.leaf ((nat_lit% "1760678376030718\
    920595194774443020260464649244566384482305481701037317364916118829354283\
    224117033367293064710162528215065060361812964963354312874641360807376809\
    128126549388604005592248998937049925190993524691579013116523988147513989\
    050545273378552649636110325743070622754747674331468797369203935436569788\
    733053397273480461452580583908731806996486366061446896827528059478932770"))) (.leaf
    ((nat_lit% "227364428941967\
    678237510018588637019174285216305631029829278836277836918884934592651798\
    760463433300388990355225872581043328376760983359102681701127186617323274\
    902373637834969244906708661831997286306140486987273177426523455767279388\
    708102306743984898334852779051482200234761316016460298676478300016812642\
    363435199598553813192848198350716579590893080346005964504158229062876258"))))) (.branch 22
    (.leaf ((nat_lit% "14306178332017\
    119853345999143914076769095560640075487296269122943458598285457526702377\
    210577324125178410402564185560952777528123257836389732171948857951957993\
    244244133377498289008362407194749906289867120142459205254815462693952767\
    029006328578500373708082717135063379284036911038192557270665069813844862\
    087436512584371786775251905787116079087136776588355825701395470246084066"))) (.branch 23
    (.leaf ((nat_lit% "643856811342676\
    938891173845361613950395830598257328999046320692176853451100878711292885\
    615299282554811418535419540344780176002893785279821258183442236142679611\
    087355050263478587787000844830535708918159471947037056492164763786760429\
    113157848577471093081411219629766882201116886170648324951190868625550654\
    390948148562871612293406554415606472717032651205051492206320991182897187"))) (.leaf
    ((nat_lit% "201651460927105379616097800218344634030644111436\
    836134430649446675322897497092369916077480961550180701504641588053875005\
    052152883934960969207460937508665946598034162038146771342950276706604250\
    277404240950738128891535829335316056855315048267516742861027205138807477\
    003990951311452008456248010482966588655939639932931705891726489071189475"))))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def reasonCodesBlocks (i : ℕ) : ℕ :=
  if Nat.blt i 24 then
    Search.LookupTree.get (0) reasonCodesBlocksTree i
  else 0

/-- A bounded numeric table decoded from packed blocks. -/
noncomputable def reasonCodes (i : ℕ) : ℕ :=
  if Nat.blt i 765 then
    Code.field (reasonCodesBlocks (Nat.shiftRight i 5)) (Nat.land i 31 * 39) 39
  else 0

/-- Decode one cached reason without referring to its validity proof. -/
noncomputable def reasonData (i : ℕ) : Search.ReasonData :=
  let code := reasonCodes i
  ⟨Code.field code 0 6, Code.bitAt code 6,
    Code.field code 7 16, Code.field code 23 16⟩

/-- Shared sufficient subcubes for all contradiction and retirement steps. -/
noncomputable def reasons : Search.ReasonTable where
  size := 765
  lookup := reasonData

private theorem reasonBlock000_checked :
    reasons.checkBlock problem 256 0 = true := by
  decide +kernel

private theorem reasonBlock001_checked :
    reasons.checkBlock problem 256 1 = true := by
  decide +kernel

private theorem reasonBlock002_checked :
    reasons.checkBlock problem 256 2 = true := by
  decide +kernel

/-- Each reason is checked by the original partial-constraint evaluator. -/
theorem reasons_valid : reasons.Valid problem := by
  apply reasons.valid_of_blocks problem 256 (by decide)
  intro block hblock
  have h : ∀ i : Fin 3, reasons.checkBlock problem 256 i = true := by
    intro i
    fin_cases i
    · exact reasonBlock000_checked
    · exact reasonBlock001_checked
    · exact reasonBlock002_checked
  exact h ⟨block, hblock⟩

/-- Packed blocks for bounded numeric lookup. -/
noncomputable def bundleCodesBlocksTree : Search.LookupTree (ℕ) :=
  (.branch 8 (.branch 4 (.branch 2 (.branch 1 (.leaf ((nat_lit% "4005816\
    000707907499435758473064466287168094743330620626190158126478042337104395\
    342484793280014238216888775610810980733974068900125154700060720279820808\
    014053593518791654615522383370837249121325181911004913355099506269035340\
    270113688966560882958401266464392951407670276257186355664168889803665522\
    846115879832830000340467657308084256267408435753453306208321746058617588\
    101784826498269552924773589058176649979462612878172071610749014209827200\
    931289510745563503369148799803764095645620777435752013405630305144884980\
    701434356721500475790949233124501721890940986268149149500225975944059081\
    927506195903156876626490731218611533106624720001909283808469406686642177"))) (.leaf
    ((nat_lit% "4642006\
    563702738698376138977590719688520112182723676935600872960549486134427732\
    595831952720013919080824235023470589788004740831150829700337826897829102\
    333181764036593330980017902399331872593986103098754983745255978001095073\
    984188474163646279417622378540134196078356599368029315590906731955234358\
    162399684370379563563562472038386177754827399113579537348830801750797518\
    600193321406317880354447229853405946664921579657046992421735723696598099\
    945137380168794661186337213039484000905535037768849132761498608385364864\
    567817110334210527863932088278823291785575309745510025234441589284663861\
    742811707255865457889861157908094593483630117138721738857065985773404169")))) (.branch 3
    (.leaf ((nat_lit% "162\
    555755106820719123800720421529176640640417763367415182465003298983935553\
    018861264645453652529741324321844242452592338654835057974651942086914445\
    665693872139484244804908049560454806701595778908163624813972452701226479\
    341104700780742014094216167518084595260048732403771913101553943157864162\
    434484814620204806012237815179976008591592063274744437609345821230356908\
    549710056569923726257057143746856759392719561103687233321066726110970410\
    048337215293835402592759226364844948946547454242778042569342638423835637\
    337382811171825957943516283080269959361082274414434249668523496264395094\
    220788759194623535499114722786997543809338249772110940342159995702233350"))) (.leaf
    ((nat_lit% "31\
    298537517969663878316057000015871578516101104734151609980202984508798431\
    438086924637667748051091540745770174505131284115099703702719797717388735\
    755910932923187688669981154085515876002793800104317906973130853811315047\
    171367400948661592407565367379174582457719853345242789624405828668829938\
    557319565842301230066830481246627947003005753280756477204362281208323424\
    222507796856529797391500394070436572810102584371197348144346727978900259\
    115670783224339956614657741140319557664824219306494980563950974405361826\
    076823432963580286223913984529958053218514298666906439521022450150408154\
    510670699407513658755654997003388723172620203637486149795494439481788418"))))) (.branch 6
    (.branch 5 (.leaf ((nat_lit% "15\
    815695864546901262709992921882998472336088292619555837894974135873834081\
    647025241683267896618800352740704407287351566418109620269048849669896627\
    333235579992027171531465580174155727247570439842234102980126537113332670\
    811079367685052472104708202150856737939218624557118870863744100478891546\
    279953897427257310345657091451345813352204207527779149198128687973939059\
    469337356873932240458950691995334116186739918758143758291663634165711972\
    911987633848425406756597677502814270899657815753611535191068851788204014\
    250625954215282615740913370114985287277474898388931585774229809484315700\
    027213112145175050716734113890671899334283207889976362172941566425957636"))) (.leaf
    ((nat_lit% "22\
    301232539012718871147954324739627417055159299468803912816739356841476166\
    369438642875180120410837904167177378829846618088912960473693177270414592\
    478036786180850317621362807917549580601451780620642489981061994770019656\
    496943424706114235559805386923326895421673349927393356073079137434615224\
    512507939549982163639538434391133712700154462605153077831613846827159033\
    338158091804720964543288577888935049377480343186712704457988840252144572\
    513999069348881622461467051788961980193267685981305352277526378344534126\
    922103696924188807213299252018211078972115609170670334564733277808244583\
    685663958381135756059605607077014019507965334370466768738360472016783880")))) (.branch 7
    (.leaf ((nat_lit% "13\
    191268430333076899170849581561362839248795244433740050541929469682040647\
    842723744726381999234537729818333200773410438325962423971547581784205484\
    829888489000650136015965816666166467559504820464897773761251713133102020\
    579606873348384914283955052838059623931334867407064302176113534001656427\
    521250805574875059756129347361525696594792902727733192102877761993786274\
    907280984367260999478141994280635664706771541532537053612636871869692313\
    455600211839207137982523734041802786924196829721421225929472340751199462\
    297236820651563166022258775341109854813463484625821281818527631363444399\
    197357520255633783786536902632170167957280564640784727753192730443907104"))) (.leaf
    ((nat_lit% "113\
    887368641420615703701441348572550020671511920153967742289812922346851384\
    680665808999384865394620040588710247584419524096386453770980011115065859\
    685153543206122333526863570269432330046741730526581603032416082021406474\
    263509481753476420822451527381608001240071282841184646467448477271661506\
    808247301067454277339326840206793851471117375793029885342106090790666359\
    459831863120647031751381985531455539537331209816149904613624879647596695\
    003385039777414486754047352012470049628197462511551126213586936501773084\
    070680952361285198010043354346776826426946752878009163705264853808235396\
    640296870812246667159578095345552659049058955484742470312413041044521088")))))) (.branch 12
    (.branch 10 (.branch 9 (.leaf ((nat_lit% "45\
    227206046878065474955757704715151935869311339614929184321074891696506675\
    609392813665103271872491798551731543332058309550149647800100155999775888\
    112031121695831100389764597733782431080043776761000005454129024066176144\
    433896564844850743527211042747629617078554440162424109043477512155703959\
    147537956395162051248589455507248363695766570750991551564185881327297464\
    167290353089964470670464758218981093930072854188696099439632064959078884\
    380165505633333893193784645955049415014504635439060777225278943936394899\
    116296002526170716097438751437860151513319067749873201384345785082472988\
    673297658382118441806051041698399573498282658081684958900167404561629440"))) (.leaf
    ((nat_lit% "19\
    684485965590609199395732609239616260381484295031962906261692904294314393\
    144536411157975192478073013240975590013669755416291353334418942474112167\
    852038698092148212718082511232089611639982659325589395382416824627435175\
    124419018268418048925750869653801881039940350652541461197704187948208632\
    775474105311324517003701700344264670656048133811897309314448999067986958\
    569067770168271177596938250389898493000477719982811843059774075482414431\
    835356769620645715695088054711308833641340802442708357948933446468548424\
    620254774928307869011167569772050745876361092928026611050150126102248343\
    663847463894368065667802618698434871007682979387831828983545822127850496")))) (.branch 11
    (.leaf ((nat_lit% "52\
    867490404725177759485013595872768270481988940693447169179789019048560906\
    269319616725868382051072132275156385573918534747802067587772244342854852\
    291851565717937421015063557800618388659572360989404870576088713670998578\
    913166625451010326093246058873412780289077573825808618047597929336357306\
    923115631492840834198618651615513562230703041499944291364687762213648937\
    585696405069406337737798914594826285981068131290382716928160179608653296\
    981358503789503142611691092707267899753083554073819823776276521559895032\
    432966709534754867342402602785393705956259474116131992291287991871494720\
    581904333906635102210057787690968015546845275824280129835973845249437696"))) (.leaf
    ((nat_lit% "1\
    239246842933957598533309736935892434909447154879274633982138527404954356\
    027334097130171628592627927338545849495129969284420854029746831361321633\
    629971284519349912993721871430988690400266504647829058958641246954331482\
    105536097795849315045372868080266154949639397755139278054004776737456269\
    418216066316620337038459401637242832470141330667752158930303838768672698\
    593776727169414772479854579197728121215679760329908865464529113642953289\
    899722280113692041429870599873634827255872208171664371665472752783903850\
    502650538916504382911552959415722286976171102832874077874754915663288347\
    503167786243827798387999969521157142309766229902720941786248675854467072"))))) (.branch 14
    (.branch 13 (.leaf ((nat_lit% "41\
    949953069738565771341458034921030826608577093700129642509099643621764143\
    440392210016194387579326676622890038766457950729826329284469049915662684\
    750337454970606466700864904476471457079744830720465878351953515608149196\
    216668827628533881464620909736429863131017393632602198045683083375278935\
    619849737738459809533843005831152890520921220607508373035094840671933705\
    959196717509962541218911194457086105203488633335945386491502444068611014\
    573308014918211968128649129650016389974802532953913625436754718607884976\
    289995776046716885160038570870591567131112073021403367582436214558210469\
    037165544625701290733786816849450381456162243790931792709291515989721088"))) (.leaf
    ((nat_lit% "125\
    859878497283173085613105501543788871790556257020384691964827967982796941\
    260797742860682357923560723839579289335764332016020484887139944487926306\
    247236745718018821183597204280528949727421732574171683171561692689204420\
    473914787478236851965206455820720850250184202837361049999240978663247310\
    865262646793637840085543795428280229613309556744962603597343594324614837\
    773744403908657039238454317815843441405645217332779318953388690722781044\
    900296974703863727705830722991420034152026720456648301482279505534634279\
    155108397292894964506201390851763728318301873091618258061574907992699232\
    903749231421795627342548511470801957103513408484095503552288814331330560")))) (.branch 15
    (.leaf ((nat_lit% "3500999\
    007652015846884789349838528861051588480350492214837458237503749213171367\
    232916189619570163422398007242380271575766735770951680597186752148585565\
    580807119365680894614493970798094575264468716853397750911733091166549983\
    294937853868424478541340332936468921987133976920801797102948383680024843\
    049419342974400730680425374173765336832119341017378161215851104663932283\
    523568235035950906193491795892846797936850012790112610109651219591204364\
    401052865075328549349065264741276010267337711906969191932677124655131545\
    081782479994238579721082727976769813722324824973629443269624589095659887\
    125226654986572402178284370618522804627387579566729518847836736859406336"))) (.branch 16
    (.leaf ((nat_lit% "2768\
    632040476305994437120452377517681153480365347418838342218941976357233222\
    953858388132274641598307662730727192072789887793646272982851035381542098\
    806292640329928173575279383944469708084409583054840910377178610776787915\
    513175095240293087675223742530138678040514047338862445767544162938040372\
    205520043645984308670195794861611355573761608897958707201784971689236170\
    053102876771206642420978193207463944168263834609758220053648971974846235\
    245121810986567267984245486800197317308101193459451361693893773824991268\
    038527693320451926246014621595387641543745569771394394069543291047749854\
    742065597610433369037461443084385851620758487442406833102642719454396416"))) (.leaf
    ((nat_lit% "4472861963995364944071211496816881\
    509331001205534371229036575324190332617342918986061682286435858699930728\
    060010738126563217543309449024320756600701499490178824824265212584554626\
    541678371436417219778668883152049202705934294806240491520306579429628000\
    988606739264035225298984646649951535536374029290498282809486289648806982\
    878668017779524443413481774492559815664358646830438941869981346727059147\
    817144755468789241694621227519320746365532269077193580341906539710251008"))))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def bundleCodesBlocks (i : ℕ) : ℕ :=
  if Nat.blt i 17 then
    Search.LookupTree.get (0) bundleCodesBlocksTree i
  else 0

/-- A bounded numeric table decoded from packed blocks. -/
noncomputable def bundleCodes (i : ℕ) : ℕ :=
  if Nat.blt i 535 then
    Code.field (bundleCodesBlocks (Nat.shiftRight i 5)) (Nat.land i 31 * 68) 68
  else 0

/-- Packed blocks with an independent field width stored in each header. -/
noncomputable def bundleReasonCodesBlocksTree : Search.LookupTree (ℕ) :=
  (.branch 8 (.branch 4 (.branch 2 (.branch 1 (.leaf ((nat_lit%
    "1989913158703454089078693341415897940417929150903459549261746340\
    611562861718471568803531809891058552017230468685555941355703784063758873\
    544069581310873517959969469581334045892221679205729983426180614171561269\
    134028380796720953622288292709406238563276875438940224451327681601071838\
    237825519739071388152705502190948239999087068683553690478425392343206866\
    635149255855226326585442353069447259975344985239452674759342656496005726\
    783207923894452224755733304510968829056154751743717502679658702350484947\
    251819788073923704797058344169815500614652196177985374648103930750045458\
    107408884047258476826356860453043059260396870371381755425087496701383445\
    204126468195037972284396114909978309827994139553797511891696737512782607\
    987262925657848321679967026039555828832090334157903362414664088989142949\
    939716705150549506444249066510882403527429257955395735455128591725910524\
    675480061383545992518982547847328620169585495335302339606663904720431493\
    030964313428241374466335671893790987470889637116620314811511260268313858\
    867978121093047036304991146438789788788155272970288807208484845155967964\
    949453475018575703620037913844329536506268354579172001575776742553412542\
    405490632442183486441614853216466312719245272391291891411005284357196851\
    939649028151581365995493481624381020286894680714469772108507516967307530\
    677401734394019211036027960994053066156149921630134032565309507215843728"))) (.leaf
    ((nat_lit% "4407716805169901135148\
    525567965977319365828452657050627596585777289914003298132874286048407121\
    141260961844586296702589452850648743555957404157455874343169805379353267\
    375894961153868390623729557242037385182369549404028652188686326479080073\
    317577302650174996819631815161883637234273797994935904664729654008862734\
    221216621062697186356898328749862722214683701509992643779541992797387689\
    471480204579950547421828822200849624352927598623513777783313178988399676\
    748683787645908434664218655731414175656080171087392616199901888011788908\
    576502973378730900046564132591178991589640520983658040586436329965978497\
    281075314303433887570032758126979261594256241167433680579319890674016419\
    620980926639639209365615897538391938845905970815204931511218486132090666\
    499132192058979753652939509675636452521562458625599575902994428827345198\
    472511075470476902127046418262996248737536249077316843507163948630352174\
    915842743838811626916346858109759946854967493008300283245289976426087018\
    528903040618438333165929766031036384561019478978375567234297832717195255\
    217080054884713158796755589105080458071765310639386271519650858301854197\
    392307947183698470994588556227414888447127044341289074488019653855876861\
    139312032010569220563761645018053647968155387511766632282000549324843724\
    066046349644043181377850592432160491758914092582086579675452633417264744\
    201881470934475089174835316250694415124534165545680289190005804606602536\
    077804765603851864175649559478923881207440068845780854081535381273100954")))) (.branch 3
    (.leaf ((nat_lit% "2538788644900813598\
    058282992002185693752275390950053809311066615050199839561515718147412058\
    265511466938379590971227557573718651386852687455806691523827475842073060\
    515807898203032704726072256334333904415100520294716141807272458917228371\
    433944507834250815236036781029226451432089139532498330879329592093700158\
    181873454641196697145505175563665511959416934014020026803845080032448963\
    872427491563353489034637168874115372514982715356336353448370987027501532\
    095985174350380236498022478880664085527750163488616072847829396745901358\
    527213725643533855348110470618684926046780825029336787833602607505259501\
    353728487824117711071753887996164853010982968934122755847111187758461301\
    870892867483237779323533097871104845231142694294084277606486197316637611\
    313467315258528760071186656422262667168873239210969210649264061140802307\
    506639697890934188172834160234307757673596915938962467921334433921810913\
    619721963598643294510071831602250275921107980871866317879547876695423598\
    248907146527140035328366253616559761241506776952347052194523024399115386\
    194173388178098040357687509064352827788567851783713382624650000706921793\
    844242599501632887829805007372018738508286593687315258402629581838657694\
    398862219242802357298529755054372631076963855580643921174700005014246581\
    822854665672291544013136400059402580388840095173423034306556297895056371\
    838359188757937640996117522212307124419022497533713025447889339536148181\
    470589867773873078496634312295633023033494442417345021035800802843757722"))) (.leaf
    ((nat_lit% "119093182922572612\
    768830399967389048110355224404293876351034206039732127271911930870733277\
    561914481253781685760836713532189587626438843742422896576940975724928779\
    359612514582886075847099551023403364111826393495366685401729108719111647\
    880170728602716985887488476343941815851396009347003275666713677803013928\
    596728514252904117602691180666926012029718162577541403823293455285967207\
    680931730410128001460069041501069984309161182885983366004757690976393549\
    640691925390587712847567436428768745150636379354618104613197879121826767\
    756557783552766080797939805208909210708858654725070619169352379782280307\
    364677062911940685669669696559418759175670925428282496329708511299461392\
    370936227588334365775759183614973628112084745482287568773037537923322373\
    343130650683485252596154864499138595708793285350893229292378027544950353\
    088429770076782119874379563996355545024112688232063994677027496370098323\
    234467847997644007079638674698815302001206562152512029396250417345738580\
    303211023651967155518568877031170117139493051448803131178011546164024454\
    116105051915128556480879350218200486120942383094399967526786914889069231\
    305537807159889037181081549665769184019805527820428887695289447096595836"))))) (.branch 6
    (.branch 5 (.leaf ((nat_lit% "117501046568804619462975302251134961\
    586459780626796918683904481039450591118673080496853582967816470116537915\
    203571650218061325902183143554617829073410960814542942029461803733241913\
    829459362540396136308135775306551021039762238804133329059849558365894729\
    497484404637458533283620679758428634509516651781370713411675733608765028\
    056104621305123352289040010706303520146205238111585420192531895759305932\
    975112258071875640107908635102334454407479655608519584958380655200271362\
    660453126448390417245108169100503128853731846885820392510035192915047454\
    607962313332225698036994840580139192343273292145238545241998456973389878\
    843699356009977791910245778855083636160468322541491967276417441699633427\
    270929564361579470773005150622075423803040648938975316772444791901067941\
    861363973428555734943680822099369463827649667519829920100941281781369571\
    843591465518788493774185363516748726946971104916675061553666113685717685\
    910198469921005663070858929590510225384762664940206521185740256212565903\
    058442420120499220559484189010309972185737074940285813378393215168166780\
    241980240013592952573635994618689740740239236048521528075911332952912841\
    692811231410356783722200440336564696725453238447137250575426543501554703\
    332507034556821102610113282514839870785794744490951629862504590358005126"))) (.leaf
    ((nat_lit% "135919432005542102422901587521889569339931256268885426570611959868123\
    378794099943732867667235715664791278686972750603128009993924745806152552\
    359629782362287992187815535754715040987423209200874099201951763444637472\
    972945269779976903196576163908446151662553748919842281861761211008501245\
    096190015301876536197985667267705354967534413290400980432848490201994676\
    840902599677756270958402886214875417654409541280159936833813205048042237\
    724830655900930250162108560454919507290851341874190934906784628357961281\
    847121678215957235690256173902772490976058621218090817391781173689031888\
    702400817243870136937692773025271730481266010620285496512079859116772185\
    722005729833109063947551876397614125315213956999033426361868449549420024\
    790410381440255174774895764772003398882544710850607511252065216398805684\
    906750567287861654228267270702156390131622625706007961909492093887162476\
    103251515677895321760837587939636929747731590635077945620132450475809501\
    079896362060178512579519027069229519663921732747570662083125373635242925\
    167516231777083263428757201655800013238165393023304677030639924135863154")))) (.branch 7
    (.leaf ((nat_lit% "15495616330927138268399509247957453370787\
    387366043670034152765664746702238790290362444131347793780416662735265936\
    005384624061476576078101192621616663119697175924361280971308388604346916\
    207637248472823319001268828721097402735283883271964402859281179133132836\
    971531289501821019224937852126107339000774664591028778875254510822327550\
    159394308739839847352416758701347486494936782224532520570562804059976532\
    985030789104900365556707064564558117723328440910071478473959524296716247\
    859859444320088784368921039930962374325245599979275271192145193799022424\
    701395734236861997650012758253976763919032166655113506976278413099252890\
    542574821714360064761343455959348631255788493732679423761836814020786110\
    257927916772381043208189876393246200104998086141847048462369948700213977\
    386328584700845736541122861444631179010235162647653901607317385003853296\
    382462289108507215825634448774330762878582756897414604726801800281431732\
    141857841390245129716003370248834206662810101511610415873412459902911080"))) (.leaf
    ((nat_lit% "349349198132273314552\
    539322918919420653609459128169097754619828374564795645145211892877535924\
    304152870494049144824735311110167637279741856292319202681002486152812673\
    395883790113861049167127078577498782406499318113922279043692313143015647\
    944326018114668219717734745624548171634678744182731904270169021301777483\
    585901217028889742988769587898402849437653853441751136755818554998116954\
    094263584976510280179119136084812715905126210958630441205996700393790508\
    849753901695445982816998645790769682541405755337152142051895469442547159\
    267899244109661810645548880449321733944016398633755203252444126520037694\
    361566911991800463121257572904310646140065974054311996927165476017141345\
    025792143445471233493396720414296530704070972508923011155227387362824027\
    544023468834879774226109524192440329078454687181204493255895827086570539\
    449051063085001230093063381679506124366516859307126454752986069154653792\
    203002584355986020881532844956642682257506423773761570342628224380793605\
    791402071341074145400419321751058931684635859647615431609443812030106952\
    735115189732959103766535387162245101755385645297767481737415834046465397\
    533853204870954937770760091654951254034005509678705306600903729937327228")))))) (.branch 12
    (.branch 10 (.branch 9 (.leaf ((nat_lit% "114710956788\
    250178247678564182496790895471688305030769093272346268894461073695051310\
    112804440362245039091677357654410783379633699255080676586764898614132464\
    307470188842911788438710306741572213114972038016763568978225619582039161\
    149287625056941055460746479140944374765616554781067878217571646638695101\
    452644682441403792958414876138164411182161991554499907427020883449023688\
    458456603602975458216672400040281185651463809323601505373926904691349634\
    639039438459261660920800245682420700232979774628678236881963242543477967\
    219933448306096917736829757473960535575559975882111369515466630016446887\
    275232618047036043138387966413733032701932944338955878861517085941272299\
    564252922668338279556048532029670036248126202239139007600232411402868246\
    800387858726744720160513491779524372504715524849024691362753671984927523\
    333658069079279149580844077101283910947107533233394954440259702236542762\
    130213689135546208859586898847334740576227868648949506574876497873582133\
    093079712017643274351600796111518145259512088036856114375570330719185198\
    259452611380504768649884135543036015021218547958010012401494604494193859\
    961662393977097852344581152838257128634563162980553825502134987263648892"))) (.leaf
    ((nat_lit% "8\
    832089685129774326742547323325800631038850276693906878375713786902981622\
    095798308265845797924989419071922498254049557756206515686158565676835463\
    643075712586063335044575821585040583833829680219319265437255699249255116\
    472967230169569427824945207380721202121756045626229770148751971872039726\
    756797686206456519882250195123900672053325847533792162667813736653828807\
    803546456321675805345674809374274490614900238114110773113105909339264182\
    590190112120671407647383686492374664020017865784457378355265170010899212\
    274745919052394034400569824856917797786446371764922071223291407221608547\
    696299359895554657388279881074997343461668994908107966971695324157330954\
    340914725642882745391512423744302246230863778849609881455097158206824865\
    539578942269161203318437735691327403685937423163797773224294577148277332")))) (.branch 11
    (.leaf ((nat_lit% "10\
    976111278891495742449195549454705816904713764799941517187065494993819549\
    209061618465672350326844624137066871972001206799900507884674899572800225\
    471069832112755810451770198272636446646643661838011519298931052971005545\
    846953395954787549986222899087325319752206004128613544058828486122817073\
    062935950286531264611099049961321568093607535855264839432753711539400153\
    633923801890691598863176072366892654927672174128887042366693036415632586\
    114630326573626819516393726352997035427851680069303534087407825100790894\
    472253035986528638951387244943848311765419642677104114085901844567056010\
    414731538070722480201957509322449073268610616474503103786133373882624165\
    389706677642357996669364779435353637405753987123220973648576693273482413\
    376403168500952519939862804884087887581361477219833351456934050571207252"))) (.leaf
    ((nat_lit% "7807332798960551228156934379096441736093621722058939\
    560398795886088143833249198307078557350006063446824854148016189921429136\
    930354857325490052617311042332012047947481893372106355023328002287541839\
    307096665135367360188494530797484730030306596723998446650606422576934317\
    266445891918247319800927568044892932010946206037741972110895898406493805\
    778296567323598651210770379677728658808178030065622900167306315557686537\
    050018046958281519630687705685901348801648832852178300978722486229537420\
    495676712482462814162175166259505552718670595936679558713105565889956531\
    784669142492197222598834598475459817196184018784719489523882278375004119\
    676547776960559524783950607547571222776179718943404963065925947658310218"))))) (.branch 14
    (.branch 13 (.leaf ((nat_lit% "4254722015309565444522207198114074\
    770797663502055400068860135569334615565688669057756802959220980964805373\
    920668452894894424094591829462412342591299133673394098241400756992292736\
    581097050021213950770813111827113879478461343894757389841711085319998050\
    091082182724682984282347202830007444821637362480923420903155047803348422\
    482352589960583875079617451504441719605189691281762832036954821005649710\
    385406672118306352514696129303917275930234294757568103645301000621418349\
    893228704689695184597151941175459359114841315409812570581970014650910268\
    942591310200893715609448755584774693297920939442651878892716070840804160"))) (.leaf
    ((nat_lit% "1895717\
    187416100589380547993466037359255708792925093501706721836325491080283009\
    129163029099901851274387669361672266358718787102961262921172140877483028\
    192936587506831860916492357652705675282024022744121852585870663043212342\
    669562525200304815018845507273977917019650009385785555011976873879484629\
    512166557223919204502328258005865725181090316569952410276959741300761060\
    155815127440918816801359841669009177709330522775039694217787019813577126\
    749451633313986460625334649760922463914080722331142344814707220607157302")))) (.branch 15
    (.leaf ((nat_lit% "514752019732615394219869272574228528\
    269775980996468324793849202180644574048390670577945317863823130645073546\
    181072045139897816113942552735432334528667890019613332925424641401750393\
    639229023888602391912141478005432454164454939043448829073573811979153063\
    788712731823151003683778925735333127847492377967782902703449450559488290"))) (.branch 16
    (.leaf ((nat_lit% "295628922691267700\
    792720777340773811440351024145523735366127820093590705648113010286288956\
    340102446816380585610162557569472952898603853870856291860025157435892400\
    528044703006986429892387671522055866002774922936086500177354890309845528"))) (.leaf
    ((nat_lit% "2749961220610465549913\
    587874619638388006008301728871958128530922469662559532861763360775184589\
    032097015308135378143667645848803249544109228643824988481144075915579928"))))))))

/-- Bounded lookup through closed balanced data. -/
noncomputable def bundleReasonCodesBlocks (i : ℕ) : ℕ :=
  if Nat.blt i 17 then
    Search.LookupTree.get (0) bundleReasonCodesBlocksTree i
  else 0

/-- Bounded lookup through the adaptive-width packed blocks. -/
noncomputable def bundleReasonCodes (i : ℕ) : ℕ :=
  if Nat.blt i 535 then
    let block := bundleReasonCodesBlocks (Nat.shiftRight i 5)
    let width := Code.field block 0 8
    Code.field block (8 + Nat.land i 31 * width) width
  else 0

/-- The positive reasons used to validate one cached retirement bundle. -/
noncomputable def bundleReasons (i : ℕ) : List ℕ :=
  let code := bundleReasonCodes i
  Search.decodeBundleIndices 10 (Code.field code 0 4)
    (Nat.shiftRight code 4)

/-- Decode the masks used by one retirement step. -/
noncomputable def bundleData (i : ℕ) : Search.BundleData :=
  let code := bundleCodes i
  ⟨Code.field code 0 36, Code.field code 36 16,
    Code.field code 52 16⟩

/-- Consecutive retirements certified by unions of independently checked reasons. -/
noncomputable def bundles : Search.BundleTable where
  size := 535
  lookup := bundleData
  reasons := bundleReasons

private theorem bundleBlock000_checked :
    bundles.checkBlock reasons 256 0 = true := by
  decide +kernel

private theorem bundleBlock001_checked :
    bundles.checkBlock reasons 256 1 = true := by
  decide +kernel

private theorem bundleBlock002_checked :
    bundles.checkBlock reasons 256 2 = true := by
  decide +kernel

/-- Every cached union is checked against its constituent positive reasons. -/
theorem bundles_valid : bundles.Valid reasons := by
  apply bundles.valid_of_blocks reasons 256 (by decide)
  intro block hblock
  have h : ∀ i : Fin 3, bundles.checkBlock reasons 256 i = true := by
    intro i
    fin_cases i
    · exact bundleBlock000_checked
    · exact bundleBlock001_checked
    · exact bundleBlock002_checked
  exact h ⟨block, hblock⟩

private noncomputable def certificateTree00000 : Counting.Certificate :=
  certificate_lit% "s 452 b 15 b 14 b 13 b 12 s 449 f 2 1 562 s 451 b 11 f 10 0 231 s 328 f \
    8 1 437 s 419 f 6 1 464 s 279 b 9 s 4 f 7 1 74 s 187 f 5 1 99 s 171 b 4 \
    f 3 1 15 s 73 a s 83 b 3 r 590 b 1 b 0 s 468 a s 469 a b 0 r 591 s 470 a \
    f 3 1 21 s 154 f 4 0 117 s 265 f 7 0 344 f 5 0 368 s 64 b 1 b 0 s 10 a s \
    12 a b 0 s 10 a s 12 a s 92 f 9 1 263 s 353 f 10 1 328 f 7 0 345 f 5 0 \
    369 f 6 0 406 s 411 r 443 s 180 b 11 f 8 1 437 f 4 0 445 f 10 0 469 s \
    431 f 3 1 15 s 236 f 6 1 265 s 74 b 9 s 5 f 2 0 350 s 367 b 7 s 293 f 5 \
    0 320 s 448 f 0 0 83 s 186 a f 0 1 86 s 294 f 5 1 321 s 196 a s 48 f 7 1 \
    352 s 385 f 5 1 383 s 295 b 2 f 0 1 80 s 199 a s 193 a s 98 f 10 1 470 f \
    7 1 480 s 441 f 5 1 519 s 224 f 4 1 442 s 404 b 9 f 0 1 26 s 112 b 8 f 3 \
    0 198 f 2 0 232 f 6 0 267 s 1 f 1 0 121 s 237 a f 1 1 154 s 297 f 6 1 \
    330 f 2 1 348 s 242 b 3 s 0 a s 33 a s 61 b 8 f 0 1 55 s 194 f 3 1 153 s \
    113 b 6 s 464 a s 461 a s 160 b 6 f 0 1 28 s 194 f 3 1 118 s 115 r 573 s \
    121 b 3 f 2 1 233 s 190 a s 314 b 2 f 0 1 80 s 194 a s 188 a s 413 b 12 \
    f 2 1 448 f 8 0 482 f 6 0 498 s 422 b 11 f 10 0 230 s 312 b 9 s 3 f 3 0 \
    32 s 148 f 7 1 74 s 184 f 5 1 99 s 214 f 4 1 126 s 76 r 592 s 173 f 7 0 \
    344 f 5 0 368 s 291 b 4 f 3 1 15 s 67 b 1 s 400 b 0 s 10 a s 12 a s 406 \
    b 0 s 10 a s 12 a s 78 b 3 s 102 r 593 s 139 b 1 s 401 b 0 s 11 a s 25 a \
    s 406 b 0 s 10 r 594 s 26 a s 92 f 10 1 239 s 331 f 3 1 295 s 354 f 7 0 \
    478 f 5 0 521 s 38 f 9 1 82 s 217 r 204 s 180 b 11 f 4 1 159 s 286 f 8 0 \
    481 f 10 0 501 f 6 0 522 s 81 f 3 0 235 s 105 b 9 s 0 f 2 0 349 s 366 b \
    7 f 5 0 320 s 448 f 0 0 83 s 182 b 1 s 401 a s 406 a f 0 1 85 f 5 1 321 \
    s 198 b 1 s 401 a s 406 a s 60 f 7 1 351 s 385 f 5 1 382 s 368 b 2 f 0 1 \
    79 s 194 b 1 s 401 a s 406 a s 188 b 1 s 401 a s 406 a s 91 b 10 f 4 1 \
    129 s 272 f 3 1 238 f 6 1 265 s 349 f 2 1 503 f 8 1 522 r 541 s 232 b 9 \
    f 0 1 81 s 133 b 8 f 3 1 206 s 320 f 2 0 349 s 381 f 6 0 385 s 391 f 4 1 \
    447 f 7 1 479 f 5 1 518 s 39 a s 274 f 2 1 348 f 6 1 388 s 259 b 7 f 4 1 \
    205 s 348 f 5 0 370 s 304 b 3 s 0 a s 33 a f 5 1 372 s 384 b 4 f 3 1 201 \
    s 43 a s 301 b 3 s 0 a s 33 a s 62 b 8 f 3 1 203 s 319 f 7 1 351 s 432 f \
    5 1 555 s 141 b 6 s 464 b 4 f 2 1 447 s 192 b 1 s 400 a s 406 a s 405 b \
    2 f 0 1 80 s 194 a s 188 a s 461 b 4 f 1 1 424 f 2 1 447 s 191 a s 405 b \
    2 f 0 1 80 s 194 a s 188 a s 162 b 7 f 4 1 202 s 405 f 5 0 554 s 253 f 6 \
    1 294 s 125 b 3 f 2 1 233 s 190 a s 314 b 2 f 0 1 80 s 200 a s 188 a f 5 \
    1 555 s 387 b 6 f 3 1 293 s 143 r 573 s 129 b 4 f 3 1 201 s 315 f 2 1 \
    447 s 189 a s 302 b 3 f 2 1 233 s 190 a s 314 b 2 f 0 1 80 s 194 a s 188 \
    a s 415 b 13 b 12 r 605 s 177 b 11 f 2 0 483 f 10 0 502 s 281 b 9 s 7 b \
    8 f 3 1 211 f 5 1 234 s 350 f 7 1 320 s 361 f 6 0 471 s 71 f 4 0 444 s \
    428 f 1 0 449 s 418 a f 6 1 472 s 359 b 7 f 4 1 210 s 324 f 5 0 320 s 86 \
    f 0 0 83 s 308 f 3 0 87 s 183 r 606 f 5 1 321 s 356 b 4 f 3 1 15 s 210 f \
    1 1 450 s 75 a s 82 b 3 f 0 1 84 s 194 r 607 s 209 b 1 b 0 s 487 a s 488 \
    a b 0 r 608 s 489 a s 46 f 3 1 34 s 169 f 4 0 117 s 264 f 7 1 210 s 333 \
    f 5 1 299 s 68 b 8 f 6 0 471 f 1 0 449 s 417 a f 1 1 451 f 6 1 472 s 426 \
    a s 91 f 7 1 480 s 226 b 10 f 9 1 31 f 4 1 132 f 6 1 183 s 322 f 5 1 383 \
    s 392 r 423 s 289 f 5 1 519 s 363 b 9 f 0 1 29 s 159 f 1 1 131 s 277 f 8 \
    1 353 f 6 1 388 s 118 b 4 f 3 1 201 s 42 a s 298 b 3 s 0 r 610 s 45 a s \
    51 b 8 f 3 1 203 s 207 b 6 s 464 b 4 f 1 1 123 s 240 a s 246 a s 461 b 4 \
    f 1 1 123 s 239 a s 246 a b 6 f 3 1 293 s 205 r 573 s 467 b 4 f 1 1 124 \
    s 267 f 3 1 201 s 202 a s 247 b 3 b 2 f 0 1 79 s 194 a s 188 a s 201 a s \
    410 b 12 r 605 s 177 b 11 f 8 1 484 f 6 1 523 s 360 b 10 f 4 1 128 s 80 \
    b 9 s 3 f 3 0 32 s 149 f 2 0 350 s 101 r 611 s 46 f 3 1 21 s 156 f 7 1 \
    352 s 385 f 5 1 383 s 109 b 2 b 1 b 0 s 490 a s 491 a b 0 r 613 s 492 a \
    b 1 b 0 s 490 a s 491 a b 0 r 613 s 492 a s 89 f 7 1 386 f 9 1 387 f 5 1 \
    407 s 49 b 4 f 3 1 201 s 204 b 2 f 1 1 446 s 424 a s 421 a s 299 b 3 r \
    706 s 201 b 2 b 1 b 0 s 532 a s 533 a b 0 r 707 s 534 a b 1 b 0 s 532 a \
    s 533 a b 0 r 707 s 534 a s 94 b 10 f 6 1 542 s 288 f 8 1 522 s 275 f 5 \
    1 389 s 433 f 9 1 390 s 50 f 7 1 352 s 227 r 571 s 229 b 9 f 8 1 353 f 6 \
    1 388 s 369 r 611 s 52 b 8 f 3 1 203 s 319 f 7 1 351 s 208 b 6 f 5 1 294 \
    s 346 b 4 b 2 f 1 1 446 s 427 a s 421 a s 423 a s 389 b 5 f 4 1 292 s \
    347 b 2 b 1 b 0 s 523 a s 524 a b 0 r 700 s 525 a b 1 b 0 s 523 a s 524 \
    a b 0 r 700 s 525 a s 345 b 4 b 2 f 1 1 446 s 424 a s 421 a s 423 a s \
    370 b 7 f 4 1 202 s 303 r 621 b 6 f 3 1 293 f 5 1 382 s 206 r 573 s 388 \
    b 5 f 4 1 292 s 300 r 574 s 467 b 4 f 3 1 201 s 203 b 2 f 1 1 446 s 424 \
    a s 421 a s 299 b 3 r 623 s 201 b 2 b 1 b 0 s 512 a s 513 a b 0 r 624 s \
    514 a b 1 b 0 s 512 a s 513 a b 0 r 624 s 514 a s 450 b 14 b 13 b 12 b \
    11 f 8 1 437 s 420 f 10 0 469 s 434 f 6 1 525 s 278 b 9 s 4 f 7 1 74 s \
    187 f 5 1 99 s 172 b 4 f 3 1 15 s 73 b 2 s 379 a s 383 a s 83 b 3 r 590 \
    b 2 s 379 b 1 b 0 s 468 a s 469 a b 0 r 591 s 470 a s 383 b 1 b 0 s 468 \
    a s 469 a b 0 r 591 s 470 a f 3 1 21 s 155 f 4 0 117 s 63 b 7 s 290 b 5 \
    s 338 b 2 s 436 b 1 b 0 s 10 a s 12 a b 0 s 10 a s 12 a s 440 b 1 b 0 s \
    10 a s 12 a b 0 s 10 a s 12 a f 0 1 1 s 342 f 2 0 368 s 20 a s 296 b 5 f \
    0 1 3 s 337 f 2 0 371 s 22 r 570 s 30 b 2 s 379 a s 383 a s 92 f 9 1 243 \
    s 353 f 10 1 328 s 411 r 443 s 179 b 11 f 8 1 437 f 4 0 445 f 10 0 469 s \
    434 f 6 1 525 s 446 f 3 1 15 s 72 b 9 s 5 b 7 s 293 f 5 0 320 f 2 1 354 \
    s 398 f 0 0 83 s 185 a f 0 1 86 s 294 f 5 1 321 s 195 b 2 s 435 a s 440 \
    a s 47 b 7 s 293 b 5 s 341 b 2 s 435 a s 440 a s 343 b 2 s 435 a s 440 a \
    s 294 b 5 s 340 r 570 s 344 b 2 s 435 a s 440 a s 98 f 10 1 470 s 233 f \
    4 1 442 s 403 b 9 f 0 1 26 s 158 f 7 1 212 f 8 1 242 f 6 1 269 f 5 1 291 \
    s 117 f 1 1 125 s 241 b 3 s 0 a s 33 a s 57 b 8 f 0 1 55 f 3 1 153 s 284 \
    f 7 1 479 f 5 1 517 s 114 b 6 s 464 a s 461 a s 161 b 7 f 6 1 524 s 122 \
    b 5 s 466 a s 463 a s 444 b 6 f 0 1 28 f 3 1 118 s 282 f 5 1 540 s 116 r \
    573 s 123 b 5 r 574 s 467 a s 412 b 12 b 11 b 10 s 311 b 9 s 3 f 3 0 32 \
    s 148 f 7 1 74 s 184 f 5 1 99 s 214 f 4 1 126 s 77 r 592 s 174 b 8 s 430 \
    b 7 s 292 b 6 s 439 b 5 s 339 b 4 f 3 1 15 s 67 b 2 b 1 s 400 b 0 s 10 a \
    s 12 a s 406 b 0 s 10 a s 12 a b 1 s 400 b 0 s 10 a s 12 a s 406 b 0 s \
    10 a s 12 a s 78 b 3 s 102 r 593 s 139 b 2 b 1 s 401 b 0 s 11 a s 25 a s \
    406 b 0 s 10 r 594 s 26 a b 1 s 401 b 0 s 11 a s 25 a s 406 b 0 s 10 r \
    594 s 26 a f 0 1 1 f 4 1 155 s 285 f 3 0 288 f 2 0 368 s 13 b 1 s 401 a \
    s 406 a f 3 1 21 s 166 f 1 1 425 f 2 0 497 s 65 b 5 f 4 0 289 s 234 r \
    595 f 0 1 1 f 4 1 155 s 18 a f 4 1 126 s 270 f 3 0 197 s 84 f 6 0 21 s \
    103 b 5 f 0 1 2 f 2 0 371 s 21 r 568 s 31 b 2 s 376 b 1 s 401 a s 406 a \
    s 382 b 1 s 401 a s 406 a f 3 1 52 s 66 b 7 f 4 0 199 s 235 f 5 0 155 s \
    263 r 596 f 4 1 126 s 251 b 6 f 5 0 288 f 2 0 371 s 390 f 1 1 426 s 437 \
    f 0 1 3 s 19 r 569 f 5 1 289 s 29 b 2 s 379 b 1 b 0 s 471 a s 472 a b 0 \
    r 597 s 473 a s 383 b 1 b 0 s 471 a s 472 a b 0 r 597 s 473 a s 88 f 2 0 \
    231 s 335 f 9 1 318 s 212 b 8 s 430 b 7 s 364 b 6 s 442 f 5 0 539 s 386 \
    b 4 s 266 f 3 0 180 f 0 0 23 s 152 f 1 0 119 s 8 a f 3 1 104 s 252 f 1 1 \
    422 f 0 1 5 s 15 a f 5 1 384 s 393 f 1 1 425 s 245 f 4 1 157 s 120 b 3 f \
    0 1 0 s 16 a s 32 a s 372 f 6 1 516 s 131 f 1 1 425 s 407 b 5 f 0 1 3 s \
    23 b 4 s 266 f 3 0 180 s 153 a f 3 1 104 s 167 a s 27 f 4 1 157 s 220 b \
    3 s 151 a s 165 a f 3 1 53 s 216 f 7 1 347 s 136 b 6 f 5 0 539 f 0 1 3 s \
    24 r 696 s 408 b 5 f 0 1 3 s 23 r 696 s 27 f 4 1 157 s 269 b 1 b 0 s 515 \
    a s 516 a b 0 r 697 s 517 a s 93 b 10 f 2 0 262 f 9 1 319 s 175 r 571 s \
    176 f 9 1 82 s 213 b 8 f 7 0 478 s 365 b 6 s 438 f 5 0 520 s 380 b 4 b 3 \
    f 0 0 24 s 150 f 1 0 120 s 9 a s 36 f 1 1 122 s 238 a s 222 b 3 f 0 1 27 \
    s 14 r 598 s 35 b 2 b 1 b 0 s 474 a s 475 a b 0 r 599 s 476 a b 1 b 0 s \
    474 a s 475 a b 0 r 599 s 476 a f 5 1 384 s 393 f 2 0 498 s 377 b 4 f 3 \
    1 22 s 166 f 1 1 122 s 34 a s 119 b 3 f 0 1 0 s 17 r 600 s 37 b 1 b 0 s \
    477 a s 478 a b 0 r 601 s 479 a f 7 1 347 s 373 b 6 f 2 0 499 f 5 0 539 \
    s 378 r 573 s 127 f 5 1 406 s 28 b 4 b 3 b 2 s 379 b 1 b 0 s 480 a s 481 \
    a b 0 r 602 s 482 a s 383 b 1 b 0 s 480 a s 481 a b 0 r 602 s 482 a s \
    483 b 2 s 379 a s 383 a b 3 r 603 b 2 s 379 b 1 b 0 s 484 a s 485 a b 0 \
    r 604 s 486 a s 383 b 1 b 0 s 484 a s 485 a b 0 r 604 s 486 a s 179 b 11 \
    f 4 1 159 s 79 b 10 b 9 s 3 f 3 0 32 s 149 f 8 0 237 f 6 0 266 s 99 b 7 \
    f 5 0 320 f 2 1 354 s 397 f 0 0 83 s 181 b 1 s 401 a s 406 a f 0 1 85 f \
    5 1 321 s 197 b 2 b 1 s 401 a s 406 a b 1 s 401 a s 406 a s 58 b 8 f 3 0 \
    235 f 6 0 266 s 104 b 7 b 5 s 453 b 2 b 1 s 401 a s 406 a b 1 s 401 a s \
    406 a s 454 b 2 b 1 s 401 a s 406 a b 1 s 401 a s 406 a b 5 r 568 s 456 \
    b 2 b 1 s 401 a s 406 a b 1 s 401 a s 406 a f 3 1 52 s 215 f 7 1 200 s \
    313 f 6 1 265 f 5 1 290 s 106 b 2 s 435 a s 440 a s 310 f 2 1 500 f 8 1 \
    230 s 318 b 9 f 3 0 4 f 0 1 25 r 56 s 55 b 7 b 6 f 5 1 540 s 221 b 3 f 0 \
    1 27 s 110 a s 135 a s 126 b 5 f 3 1 104 s 215 a s 219 a b 6 f 5 1 540 s \
    221 b 3 f 0 1 27 s 110 a s 135 a s 126 b 5 f 3 1 104 s 215 a s 219 a s \
    97 b 10 f 4 1 129 s 272 f 2 1 503 s 257 f 6 1 261 s 330 r 571 s 231 b 9 \
    f 0 1 81 s 133 b 8 f 7 1 479 s 374 b 6 f 5 1 515 s 394 b 4 f 3 1 127 s \
    40 b 2 b 1 s 400 a s 406 a b 1 s 400 a s 406 a s 250 b 3 s 0 a s 33 a s \
    256 b 5 f 2 1 405 s 397 b 4 f 3 1 158 s 283 f 1 1 424 s 41 a s 273 b 3 s \
    0 a s 33 a s 393 b 4 f 3 1 156 s 283 f 1 1 424 s 41 a s 268 b 3 s 0 a s \
    33 a s 276 b 7 f 2 1 346 s 375 b 6 f 5 1 540 s 445 r 573 s 260 b 5 s 466 \
    b 4 b 3 s 0 a s 33 a b 3 s 0 a s 33 a s 463 b 4 b 3 s 0 a s 33 a b 3 s 0 \
    a s 33 a s 371 b 6 f 5 1 540 s 395 r 573 s 255 b 5 f 2 1 405 s 397 r 574 \
    s 396 b 4 b 3 s 0 a s 33 a b 3 s 0 a s 33 a s 59 b 8 f 7 1 479 s 432 b 6 \
    f 5 1 515 s 443 b 4 f 3 1 127 s 140 b 2 b 1 s 400 a s 406 a b 1 s 400 a \
    s 406 a s 250 b 3 f 0 1 27 s 111 a s 137 a s 130 b 5 b 4 f 3 1 158 s 283 \
    f 1 1 424 s 168 a s 271 b 3 f 0 1 54 s 157 a s 165 a b 4 f 3 1 156 s 283 \
    f 1 1 424 s 168 a s 268 b 3 f 0 1 54 s 157 a s 165 a s 163 b 7 b 6 f 5 1 \
    540 s 445 r 573 s 132 b 5 s 466 a s 463 a b 6 f 5 1 540 s 445 r 573 s \
    128 b 5 r 574 s 467 a s 414 b 13 b 12 r 605 s 178 b 11 b 10 s 280 b 9 s \
    6 b 8 f 3 1 208 f 5 1 234 s 350 f 7 1 320 s 362 f 6 0 471 f 2 1 485 s 70 \
    f 4 0 444 s 429 f 1 0 449 s 418 a f 6 1 472 s 358 b 7 f 4 1 207 s 324 f \
    5 0 320 f 2 1 354 s 85 f 0 0 83 s 309 f 3 0 87 s 183 r 606 f 5 1 321 s \
    355 b 4 f 3 1 15 s 210 f 1 1 450 s 75 a s 82 b 3 f 0 1 84 s 194 r 607 s \
    209 b 2 b 1 b 0 s 487 a s 488 a b 0 r 608 s 489 a b 1 b 0 s 487 a s 488 \
    a b 0 r 608 s 489 a s 46 f 3 1 34 s 170 f 4 0 117 s 264 f 7 1 207 s 333 \
    f 5 1 296 s 69 b 8 f 6 0 471 f 2 1 485 s 447 f 1 0 449 s 416 a f 1 1 451 \
    f 6 1 472 s 425 a s 87 f 9 1 57 s 211 f 4 1 160 f 8 1 182 s 307 r 421 s \
    96 b 10 f 9 1 31 s 211 f 4 1 132 f 6 1 183 s 325 r 423 s 230 b 9 f 0 1 \
    30 s 164 f 1 1 131 s 134 b 8 f 5 1 241 f 7 1 331 s 327 b 6 s 464 b 4 s \
    399 b 3 s 0 a s 33 a s 402 b 3 s 0 a s 33 a s 461 b 4 s 399 b 3 s 0 a s \
    33 a s 402 b 3 s 0 a s 33 a s 326 b 7 f 6 1 268 s 334 r 609 s 336 b 6 f \
    5 1 329 s 361 r 573 s 357 b 5 r 574 s 467 b 4 s 399 b 3 s 2 a s 44 a s \
    402 b 3 s 0 r 610 s 45 a s 54 b 8 b 7 b 6 b 5 s 458 b 4 f 1 1 130 s 262 \
    a s 261 a s 459 b 4 f 1 1 130 s 262 a s 261 a s 461 b 5 b 4 f 1 1 124 s \
    244 a s 249 a b 4 f 1 1 124 s 244 a s 249 a b 6 b 5 r 572 s 464 b 4 f 1 \
    1 130 s 262 a s 261 a s 461 b 5 b 4 f 1 1 124 s 244 a s 249 a b 4 f 1 1 \
    124 s 244 a s 249 a b 7 b 6 r 573 b 5 s 466 b 4 f 1 1 124 s 243 a s 248 \
    a s 463 b 4 f 1 1 124 s 243 a s 248 a b 6 r 573 b 5 r 574 s 467 b 4 f 1 \
    1 124 s 243 a s 248 a s 409 b 12 r 605 s 178 b 11 b 10 f 4 1 128 s 79 b \
    9 s 3 f 3 0 32 s 149 f 8 1 208 s 323 f 6 1 297 s 100 r 611 s 46 f 3 1 34 \
    s 138 b 8 f 7 1 209 f 5 1 234 s 305 b 6 s 456 a s 455 a s 306 b 7 f 6 1 \
    264 s 329 r 612 s 332 b 6 f 5 1 298 s 351 r 569 s 352 b 5 r 570 s 457 b \
    2 b 1 b 0 s 490 a s 491 a b 0 r 613 s 492 a b 1 b 0 s 490 a s 491 a b 0 \
    r 613 s 492 a s 90 b 9 f 3 0 4 r 56 s 56 b 8 f 4 1 181 f 5 1 240 s 145 a \
    s 287 b 7 b 6 b 5 f 3 1 105 s 142 r 701 s 223 b 4 f 3 1 33 s 144 a s 146 \
    b 3 r 702 b 2 b 1 b 0 s 526 a s 527 a b 0 r 703 s 528 a b 1 b 0 s 526 a \
    s 527 a b 0 r 703 s 528 a s 258 b 5 f 3 1 105 s 107 r 701 s 225 b 4 f 3 \
    1 20 s 108 a s 124 a s 147 b 6 r 704 s 254 b 5 f 3 1 105 s 218 r 701 s \
    223 b 4 b 3 f 2 1 236 s 317 b 1 b 0 s 529 a s 530 a b 0 r 705 s 531 a s \
    316 a s 321 b 3 r 706 b 2 b 1 b 0 s 532 a s 533 a b 0 r 707 s 534 a b 1 \
    b 0 s 532 a s 533 a b 0 r 707 s 534 a s 95 b 10 r 571 s 228 b 9 r 611 s \
    53 b 8 b 7 b 6 b 5 s 458 b 4 b 3 b 2 b 1 b 0 s 493 a s 494 a b 0 r 614 s \
    495 a b 1 b 0 s 493 a s 494 a b 0 r 614 s 495 a s 496 a b 3 r 615 b 2 b \
    1 b 0 s 497 a s 498 a b 0 r 616 s 499 a b 1 b 0 s 497 a s 498 a b 0 r \
    616 s 499 a s 460 a s 462 b 5 r 617 b 4 b 3 b 2 b 1 b 0 s 500 a s 501 a \
    b 0 r 618 s 502 a b 1 b 0 s 500 a s 501 a b 0 r 618 s 502 a s 503 a b 3 \
    r 619 b 2 b 1 b 0 s 504 a s 505 a b 0 r 620 s 506 a b 1 b 0 s 504 a s \
    505 a b 0 r 620 s 506 a s 507 b 6 b 5 r 572 s 465 a s 461 b 5 b 4 b 3 b \
    2 b 1 b 0 s 519 a s 520 a b 0 r 698 s 521 a b 1 b 0 s 519 a s 520 a b 0 \
    r 698 s 521 a s 522 a b 3 r 699 b 2 b 1 b 0 s 523 a s 524 a b 0 r 700 s \
    525 a b 1 b 0 s 523 a s 524 a b 0 r 700 s 525 a s 518 a b 7 r 621 b 6 r \
    573 b 5 r 574 s 467 b 4 b 3 b 2 b 1 b 0 s 508 a s 509 a b 0 r 622 s 510 \
    a b 1 b 0 s 508 a s 509 a b 0 r 622 s 510 a s 511 a b 3 r 623 b 2 b 1 b \
    0 s 512 a s 513 a b 0 r 624 s 514 a b 1 b 0 s 512 a s 513 a b 0 r 624 s \
    514 a"
    []

private noncomputable def chunk00000State : Counting.ActiveSearch.State :=
  ⟨⟨0, 0⟩, 68719476735⟩

private noncomputable def chunk00000Data :
    Counting.CountData Counting.ActiveSearch.State :=
  ⟨chunk00000State, 1316⟩

private noncomputable def chunk00000References :
    ℕ → Option (Counting.CountData Counting.ActiveSearch.State) :=
  fun _ => none

private theorem chunk00000_checked :
    problem.checkBundleDataChunk reasons bundles
      chunk00000References chunk00000State
      certificateTree00000 = some 1316 := by
  decide +kernel

private theorem chunk00000References_valid :
    Counting.ReferencesValid
      (Counting.ActiveSearch.modelCount problem.variables problem.constraints)
      chunk00000References := by
  intro index data h
  unfold chunk00000References at h
  exact False.elim (Option.some_ne_none data h.symm)

private theorem chunk00000_count :
    Counting.ActiveSearch.modelCount problem.variables problem.constraints
      chunk00000State = 1316 :=
  problem.checkBundleDataChunk_sound permutations_bounded reasons reasons_valid
    bundles bundles_valid
    chunk00000References chunk00000References_valid chunk00000State
    certificateTree00000 1316
    chunk00000_checked

/-- Independent fragment checks prove the complete initial model count. -/
theorem certified_count :
    Counting.ActiveSearch.modelCount problem.variables problem.constraints
      (Counting.ActiveSearch.initial problem.constraints) = 1316 :=
  chunk00000_count

/-- The exact number of isomorphism classes with this atom signature. -/
theorem count : isomorphismClassCount 2 1 = 1316 :=
  presentation.count_eq_of_initial 1316 certified_count

end Cslib.RelationAlgebra.Catalogue.Counts.I1S2N1
