/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Samuel Schlesinger
-/

module

public import Cslib.Cryptography.Foundations.SecurityGame

@[expose] public section

/-!
# Pseudorandom Generators

A **pseudorandom generator (PRG)** is a deterministic function that
stretches a short random seed into a longer string that is
computationally indistinguishable from a truly random string.

PRGs are one of the most fundamental primitives in cryptography.
Their existence is equivalent to the existence of one-way functions
(Håstad, Impagliazzo, Levin, Luby 1999).

## Main Definitions

* `PRG` — a pseudorandom generator family
* `PRG.Secure` — information-theoretic security
* `PRG.SecureAgainst` — computational security against efficient adversaries

## Design Notes

We model PRGs as families of functions indexed by the security parameter,
mapping `Seed n` to `Output n`. Security says that the output ensemble
(over random seeds) is computationally indistinguishable from the
uniform ensemble over `Output n`.

## References

* [O. Goldreich, *Foundations of Cryptography, Vol. 1*][Goldreich2001]
* [HILL, *A Pseudorandom Generator from any One-Way Function*][HILL1999]
-/

/-- A **pseudorandom generator family** indexed by the security parameter.

At each security level `n`, `stretch n` maps a short seed to a longer
output. The output must be indistinguishable from uniform. -/
structure PRG where
  /-- Seed type at security level n -/
  Seed : ℕ → Type
  /-- Output type at security level n -/
  Output : ℕ → Type
  /-- Seed type is finite (for sampling) -/
  seedFintype : ∀ n, Fintype (Seed n)
  /-- Seed type is nonempty (for sampling) -/
  seedNonempty : ∀ n, Nonempty (Seed n)
  /-- Output type is finite (for sampling) -/
  outputFintype : ∀ n, Fintype (Output n)
  /-- Output type is nonempty (for sampling) -/
  outputNonempty : ∀ n, Nonempty (Output n)
  /-- The stretching function -/
  stretch : (n : ℕ) → Seed n → Output n
  /-- The output type is strictly larger than the seed type (expansion) -/
  expansion : ∀ n, Fintype.card (Seed n) < Fintype.card (Output n)

/-- A PRG distinguisher observes a string and tries to determine
whether it was generated by the PRG or is truly random. -/
structure PRG.DistinguishingAdversary (G : PRG) where
  /-- Given the security parameter and an output string, decide
  whether it came from the PRG. -/
  distinguish : (n : ℕ) → G.Output n → Bool

/-- The **PRG security game**: the advantage of an adversary is
$$\left|\Pr_{s}[A(G(s))=1] - \Pr_{r}[A(r)=1]\right|$$
where `s` is uniform over seeds and `r` is uniform over outputs. -/
noncomputable def PRG.SecurityGame (G : PRG) :
    SecurityGame (PRG.DistinguishingAdversary G) where
  advantage A n :=
    letI := G.seedFintype n; letI := G.seedNonempty n
    letI := G.outputFintype n; letI := G.outputNonempty n
    |Cslib.Probability.uniformExpect (G.Seed n)
        (fun s => Cslib.Probability.boolToReal (A.distinguish n (G.stretch n s)))
     - Cslib.Probability.uniformExpect (G.Output n)
        (fun r => Cslib.Probability.boolToReal (A.distinguish n r))|

/-- A PRG is **(information-theoretically) secure** if its security game
is secure against all adversaries. -/
def PRG.Secure (G : PRG) : Prop := G.SecurityGame.Secure

/-- A PRG is **computationally secure** against a class of adversaries
defined by `Admissible`. -/
def PRG.SecureAgainst (G : PRG)
    (Admissible : PRG.DistinguishingAdversary G → Prop) : Prop :=
  G.SecurityGame.SecureAgainst Admissible

end
