on:
  pull_request

name: Lint and suggest

jobs:
  lint:
    if: github.repository == 'leanprover/cslib' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: leanprover-community/lint-style-action@a7e7428fa44f9635d6eb8e01919d16fd498d387a # 2025-08-18
        with:
          mode: suggest
