name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  check-toolchains:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -e
          cmp -s lean-toolchain docs/lean-toolchain

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: leanprover/lean-action@v1
