on:
  pull_request

name: Lint and suggest

jobs:
  lint:
    if: github.repository == 'cs-lean/cslib' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: leanprover-community/lint-style-action
        with:
          mode: suggest